// Ogni articolo è composto da "blocchi" (block-based content), non un
// muro di testo unico. Tipi di blocco: quickAnswer, paragraph, quiz,
// foodLink, toolLink. Questo permette di inserire elementi interattivi
// dentro il flusso dell'articolo, come richiesto dal brief originale.

export const ARTICLES = [
  {
    id: 'quante-calorie-banana',
    title: 'Quante calorie ha davvero una banana?',
    excerpt: 'Un numero semplice, ma che dice più di quanto sembri sulla frutta e sul suo posto nell\'alimentazione.',
    category: 'Calorie',
    readingTime: 4,
    emoji: '🍌',
    blocks: [
      { type: 'quickAnswer', text: 'Una banana media (circa 120 g) contiene circa 107 kcal. Il valore cambia con la dimensione, non con la varietà: più la banana è grande, più kcal apporta, in proporzione diretta.' },
      { type: 'paragraph', text: 'Il numero da solo dice poco. Quello che conta è cosa c\'è dentro quelle calorie: la banana è fatta soprattutto di carboidrati (circa 23 g per 100 g), con una piccola quota di fibre che rallenta l\'assorbimento degli zuccheri naturali.' },
      { type: 'foodLink', foodId: 'banana', label: 'Vedi la scheda completa della banana' },
      { type: 'paragraph', text: 'Il timore diffuso è che "troppo zucchero" nella frutta faccia ingrassare. In realtà il contesto conta più della singola etichetta: una banana non ha lo stesso impatto metabolico di una bibita zuccherata, anche a parità di zuccheri, perché porta con sé fibra, acqua e micronutrienti.' },
      { type: 'quiz', question: 'Quante kcal pensi abbiano 100 g di mandorle?', options: ['320 kcal', '450 kcal', '579 kcal'], correctIndex: 2, explanation: 'Le mandorle sono un alimento molto energetico: 579 kcal per 100 g, quasi 6,5 volte quelle della banana. Non "cattive": semplicemente molto dense, quindi la porzione conta più che mai.' },
      { type: 'paragraph', text: 'Ecco perché confrontare due alimenti solo per le kcal totali, senza guardare la porzione reale che si mangia, porta spesso a conclusioni sbagliate.' },
      { type: 'toolLink', to: '/confronta?a=banana', label: 'Confronta la banana con un altro alimento' },
    ],
  },
  {
    id: 'deficit-calorico',
    title: 'Come funziona davvero il deficit calorico',
    excerpt: 'Il concetto più citato (e più frainteso) quando si parla di perdita di peso.',
    category: 'Dimagrimento',
    readingTime: 5,
    emoji: '🔥',
    blocks: [
      { type: 'quickAnswer', text: 'Il deficit calorico significa consumare meno energia di quella che il corpo utilizza in un giorno. È il meccanismo alla base della perdita di peso, indipendentemente dal tipo di dieta seguita.' },
      { type: 'paragraph', text: 'Il tuo corpo brucia energia anche da fermo, per mantenere le funzioni vitali: è il metabolismo basale. A questo si aggiunge l\'energia spesa muovendosi durante la giornata e allenandosi. La somma di tutto è il tuo "fabbisogno di mantenimento".' },
      { type: 'toolLink', to: '/strumenti/fabbisogno', label: 'Calcola una stima del tuo fabbisogno' },
      { type: 'paragraph', text: 'Un deficit moderato (circa 300-500 kcal sotto il mantenimento) è generalmente più sostenibile nel tempo rispetto a un deficit drastico, che tende a portare a fame eccessiva e difficoltà a mantenere il percorso nel lungo periodo.' },
      { type: 'quiz', question: 'Saltare completamente un pasto per aumentare il deficit è generalmente una strategia sostenibile?', options: ['Sì, più deficit è sempre meglio', 'No, spesso porta a fame eccessiva dopo'], correctIndex: 1, explanation: 'Un deficit troppo aggressivo o pasti saltati spesso portano a una fame che si "ripaga" nei pasti successivi, rendendo il percorso più difficile da mantenere nel tempo.' },
      { type: 'paragraph', text: 'Il deficit calorico è un principio, non una ricetta: come raggiungerlo (quali alimenti, quanti pasti, quale distribuzione) dipende dalla situazione di ciascuno.' },
    ],
  },
  {
    id: 'quante-proteine-servono',
    title: 'Quante proteine servono davvero?',
    excerpt: 'Un intervallo, non un numero magico: dipende da peso e livello di attività.',
    category: 'Proteine',
    readingTime: 4,
    emoji: '💪',
    blocks: [
      { type: 'quickAnswer', text: 'Non esiste un numero unico valido per tutti: l\'intervallo indicativo va da circa 0,8 g per kg di peso corporeo (sedentari) fino a 2,2 g/kg per chi si allena intensamente.' },
      { type: 'paragraph', text: 'Le proteine servono soprattutto per il mantenimento e la costruzione della massa muscolare, ma anche per moltissime altre funzioni dell\'organismo. L\'idea che "più proteine mangi, più muscoli metti su" è una semplificazione: senza un adeguato stimolo allenante, l\'eccesso proteico non si trasforma automaticamente in muscolo.' },
      { type: 'toolLink', to: '/strumenti/proteine', label: 'Calcola il tuo intervallo indicativo' },
      { type: 'quiz', question: 'Un alimento con molte proteine viene automaticamente convertito in massa muscolare?', options: ['Sì, in proporzione diretta', 'No, serve anche un adeguato allenamento'], correctIndex: 1, explanation: 'La sintesi proteica muscolare richiede uno stimolo allenante (di solito di resistenza) oltre a un apporto proteico adeguato. Mangiare più proteine da solo non basta.' },
      { type: 'paragraph', text: 'Alcuni alimenti particolarmente proteici, per farsi un\'idea: petto di pollo, tonno, uova, albume, yogurt greco, legumi, tofu e tempeh.' },
      { type: 'foodLink', foodId: 'pollo', label: 'Vedi la scheda del petto di pollo' },
    ],
  },
  {
    id: 'carboidrati-sera',
    title: 'Carboidrati la sera: fanno ingrassare?',
    excerpt: 'Uno dei falsi miti più diffusi sull\'alimentazione, messo alla prova.',
    category: 'Metabolismo',
    readingTime: 3,
    emoji: '🌙',
    blocks: [
      { type: 'quickAnswer', text: 'No: l\'aumento di peso dipende dal bilancio calorico complessivo della giornata (o della settimana), non dall\'orario in cui si mangiano i carboidrati.' },
      { type: 'paragraph', text: 'L\'idea che il corpo "processi" i carboidrati in modo diverso la sera rispetto al mattino non trova conferma solida: quello che conta è quante calorie totali si assumono rispetto a quante se ne consumano, indipendentemente dalla distribuzione oraria dei pasti.' },
      { type: 'quiz', question: 'Mangiare pasta a cena invece che a pranzo, a parità di calorie totali della giornata, cambia il risultato sul peso?', options: ['Sì, significativamente', 'No, non in modo significativo'], correctIndex: 1, explanation: 'A parità di bilancio calorico complessivo, l\'orario del pasto non è il fattore determinante. Contano di più le abitudini sostenibili nel tempo.' },
      { type: 'paragraph', text: 'Questo non significa che l\'orario dei pasti non conti mai per nessuno (ad esempio per chi soffre di reflusso, o per chi si allena la mattina presto): significa solo che non esiste una regola universale "carboidrati vietati dopo una certa ora".' },
      { type: 'toolLink', to: '/mito-o-verita', label: 'Metti alla prova altri falsi miti' },
    ],
  },
  {
    id: 'cosa-mangiare-prima-allenamento',
    title: 'Cosa mangiare prima di allenarsi',
    excerpt: 'Timing, quantità e qualche errore comune prima di un allenamento.',
    category: 'Sport',
    readingTime: 4,
    emoji: '🏋️',
    blocks: [
      { type: 'quickAnswer', text: 'Un pasto con carboidrati e una quota moderata di proteine, consumato 1-3 ore prima dell\'allenamento, è generalmente una buona base. Più vicino sei all\'allenamento, più il pasto dovrebbe essere leggero e digeribile.' },
      { type: 'paragraph', text: 'I carboidrati forniscono energia rapidamente disponibile per il muscolo. Le proteine, in quantità moderata, non sono indispensabili prima dell\'allenamento (contano di più nell\'arco della giornata), ma non creano problemi se ben tollerate.' },
      { type: 'foodLink', foodId: 'riso', label: 'Vedi la scheda del riso basmati' },
      { type: 'quiz', question: 'Un pasto molto ricco di grassi appena prima di allenarsi è generalmente una buona idea?', options: ['Sì, dà energia extra', 'No, rallenta la digestione ed è scomodo durante lo sforzo'], correctIndex: 1, explanation: 'I grassi rallentano la digestione: un pasto pesante e grasso subito prima di allenarsi può causare pesantezza o disagio durante lo sforzo.' },
      { type: 'paragraph', text: 'Non esiste un\'unica combinazione valida per tutti: il modo migliore per capire cosa funziona è osservare come si sente il proprio corpo con pasti diversi, a distanze diverse dall\'allenamento.' },
    ],
  },
  {
    id: 'fibre-salute-intestinale',
    title: 'Le fibre e la salute intestinale',
    excerpt: 'Perché le fibre non servono solo a "regolarizzare", ma nutrono anche i batteri intestinali.',
    category: 'Intestino',
    readingTime: 4,
    emoji: '🌾',
    blocks: [
      { type: 'quickAnswer', text: 'Le fibre non vengono digerite dal nostro intestino, ma sono il "cibo" dei batteri intestinali, che le fermentano producendo sostanze utili per la salute della mucosa intestinale.' },
      { type: 'paragraph', text: 'Legumi, cereali integrali, verdura e frutta sono le fonti principali di fibra nella dieta. Aumentarne gradualmente il consumo (non di colpo, per evitare gonfiore) è generalmente associato a una buona regolarità intestinale.' },
      { type: 'foodLink', foodId: 'lenticchie', label: 'Vedi la scheda delle lenticchie' },
      { type: 'quiz', question: 'Tra questi due, quale contiene più fibre per 100 g?', options: ['Lenticchie cotte (7,9 g)', 'Riso basmati (1 g)'], correctIndex: 0, explanation: 'I legumi come le lenticchie sono tra le fonti di fibra più concentrate tra gli alimenti comuni, molto più dei cereali raffinati come il riso bianco.' },
      { type: 'toolLink', to: '/ricette', label: 'Scopri ricette ricche di fibre' },
    ],
  },
  {
    id: 'dieta-chetogenica-come-funziona',
    title: 'Dieta chetogenica: come funziona davvero',
    excerpt: 'Il meccanismo dietro il regime low-carb più discusso, senza semplificazioni.',
    category: 'Keto & Low Carb',
    readingTime: 5,
    emoji: '🥑',
    blocks: [
      { type: 'quickAnswer', text: 'La dieta chetogenica riduce drasticamente i carboidrati (di solito sotto i 50 g al giorno), spingendo il corpo a produrre "corpi chetonici" dai grassi come fonte di energia alternativa al glucosio.' },
      { type: 'paragraph', text: 'Questo cambiamento metabolico si chiama chetosi. Non è un interruttore magico per il dimagrimento: la perdita di peso avviene comunque tramite un deficit calorico, che in un regime chetogenico è spesso più facile da ottenere per l\'effetto saziante di grassi e proteine.' },
      { type: 'quiz', question: 'La chetosi è di per sé indispensabile per perdere peso?', options: ['Sì, senza chetosi non si dimagrisce', 'No, il deficit calorico è il fattore determinante, con o senza chetosi'], correctIndex: 1, explanation: 'Si può perdere peso con qualsiasi approccio alimentare che porti a un deficit calorico sostenuto nel tempo. La chetosi è un meccanismo, non l\'unica via.' },
      { type: 'toolLink', to: '/strumenti/fabbisogno', label: 'Calcola una stima del tuo fabbisogno' },
      { type: 'paragraph', text: 'Un regime così restrittivo sui carboidrati non è adatto o piacevole per tutti: la sostenibilità nel tempo conta quanto il meccanismo biologico.' },
    ],
  },
  {
    id: 'mito-metabolismo-lento',
    title: 'Il mito del "metabolismo lento"',
    excerpt: 'Quanto conta davvero il metabolismo basale nella storia del peso corporeo.',
    category: 'Miti alimentari',
    readingTime: 4,
    emoji: '🐢',
    blocks: [
      { type: 'quickAnswer', text: 'Le differenze di metabolismo basale tra persone della stessa età, peso e altezza esistono, ma sono generalmente molto più piccole di quanto si creda comunemente — raramente bastano da sole a spiegare grandi differenze di peso.' },
      { type: 'paragraph', text: '"Ho un metabolismo lento" è spesso usato per spiegare la difficoltà a perdere peso, ma il dispendio energetico totale dipende da molti fattori: massa muscolare, livello di attività quotidiana (non solo l\'allenamento strutturato), e le dimensioni corporee stesse.' },
      { type: 'quiz', question: 'A parità di peso e altezza, due persone hanno sempre un metabolismo basale molto diverso tra loro?', options: ['Sì, le differenze sono enormi', 'No, le differenze sono generalmente contenute'], correctIndex: 1, explanation: 'Le variazioni individuali esistono, ma la ricerca mostra che sono più contenute di quanto la percezione comune suggerisca. Il comportamento quotidiano pesa di più.' },
      { type: 'toolLink', to: '/mito-o-verita', label: 'Metti alla prova altri falsi miti' },
    ],
  },
  {
    id: 'quanta-acqua-al-giorno',
    title: 'Quanta acqua devi bere davvero al giorno',
    excerpt: 'Il famoso "2 litri" è una semplificazione: il fabbisogno reale dipende da più fattori.',
    category: 'Idratazione',
    readingTime: 4,
    emoji: '💧',
    blocks: [
      { type: 'quickAnswer', text: 'Non esiste un numero fisso valido per tutti: una stima pratica è circa 35 ml per kg di peso corporeo, con un margine in più nei giorni di attività fisica o caldo intenso.' },
      { type: 'paragraph', text: 'Il consiglio generico "2 litri al giorno" nasce da una media che non tiene conto di peso corporeo, clima, livello di attività e quanta acqua arriva già dal cibo (frutta e verdura, in particolare, ne contengono molta).' },
      { type: 'toolLink', to: '/strumenti/fabbisogno-idrico', label: 'Calcola una stima del tuo fabbisogno idrico' },
      { type: 'quiz', question: 'Una persona che fa sport intenso ha bisogno della stessa quantità di acqua di una persona sedentaria?', options: ['Sì, il fabbisogno è uguale', 'No, ne serve di più per compensare la sudorazione'], correctIndex: 1, explanation: 'L\'attività fisica aumenta le perdite di liquidi attraverso il sudore, quindi il fabbisogno idrico sale di conseguenza nei giorni di allenamento.' },
      { type: 'paragraph', text: 'Un indicatore pratico e immediato: il colore delle urine. Un giallo chiaro è generalmente un buon segno di idratazione adeguata; un giallo scuro suggerisce di bere di più.' },
    ],
  },
  {
    id: 'zucchero-naturale-vs-aggiunto',
    title: 'Zucchero naturale e zucchero aggiunto: la differenza che conta',
    excerpt: 'Non tutti gli zuccheri sono uguali agli occhi del corpo — ma non nel modo in cui si pensa di solito.',
    category: 'Zuccheri',
    readingTime: 4,
    emoji: '🍯',
    blocks: [
      { type: 'quickAnswer', text: 'Dal punto di vista chimico, lo zucchero di una mela e quello di una marmellata sono in gran parte molto simili. La differenza pratica è nel "pacchetto" che li accompagna: fibra, acqua e volume nel primo caso, zucchero concentrato e poco altro nel secondo.' },
      { type: 'paragraph', text: 'Un frutto intero porta con sé fibra, che rallenta l\'assorbimento degli zuccheri e aumenta il senso di sazietà a parità di zuccheri assunti. Un cucchiaio di marmellata, per lo stesso quantitativo di zuccheri, sazia molto meno.' },
      { type: 'foodLink', foodId: 'mela', label: 'Vedi la scheda della mela' },
      { type: 'quiz', question: 'A parità di grammi di zucchero, una mela intera sazia più o meno di un succo di mela?', options: ['Sazia di più', 'Sazia di meno o allo stesso modo'], correctIndex: 0, explanation: 'La fibra e la struttura del frutto intero rallentano la digestione e aumentano il senso di sazietà rispetto alla stessa quantità di zucchero in forma liquida o molto processata.' },
      { type: 'paragraph', text: 'Questo non rende la marmellata "un veleno": nel contesto di una dieta equilibrata, la quantità totale conta più della singola fonte. Ma sapere da dove viene lo zucchero che si mangia aiuta a fare scelte più consapevoli, non a demonizzarne una categoria intera.' },
    ],
  },
  {
    id: 'cosa-mangiare-dopo-allenamento',
    title: 'Cosa mangiare dopo l\'allenamento',
    excerpt: 'La "finestra anabolica" è più larga di quanto si creda: niente panico se non mangi entro 30 minuti.',
    category: 'Sport',
    readingTime: 4,
    emoji: '🥤',
    blocks: [
      { type: 'quickAnswer', text: 'Un pasto con proteine e carboidrati entro qualche ora dall\'allenamento è generalmente sufficiente per il recupero — non serve mangiare nei minuti immediatamente successivi.' },
      { type: 'paragraph', text: 'L\'idea di una "finestra anabolica" strettissima (30-60 minuti) nasce da studi datati e spesso mal interpretati. Ricerche più recenti mostrano che l\'apporto proteico totale della giornata conta più del timing preciso, soprattutto se hai mangiato normalmente nelle ore precedenti l\'allenamento.' },
      { type: 'foodLink', foodId: 'pollo', label: 'Vedi la scheda del petto di pollo' },
      { type: 'quiz', question: 'Se non riesci a mangiare entro 30 minuti dalla fine dell\'allenamento, comprometti seriamente il recupero muscolare?', options: ['Sì, è un errore importante', 'No, hai comunque un margine di alcune ore'], correctIndex: 1, explanation: 'La finestra utile per il recupero è più ampia di quanto si pensi comunemente: qualche ora di margine non compromette in modo significativo i risultati, se l\'apporto proteico complessivo della giornata è adeguato.' },
      { type: 'toolLink', to: '/strumenti/proteine', label: 'Calcola il tuo intervallo proteico indicativo' },
    ],
  },
  {
    id: 'digiuno-intermittente-funziona',
    title: 'Il digiuno intermittente funziona davvero?',
    excerpt: 'Non è magia metabolica: è un modo per gestire le calorie che, per alcuni, è più semplice da seguire.',
    category: 'Dimagrimento',
    readingTime: 5,
    emoji: '⏱️',
    blocks: [
      { type: 'quickAnswer', text: 'Il digiuno intermittente funziona per la perdita di peso principalmente perché aiuta molte persone a mangiare meno calorie complessive, non per un effetto metabolico speciale legato all\'orario dei pasti.' },
      { type: 'paragraph', text: 'Comprimere i pasti in una finestra oraria più stretta (ad esempio 8 ore) riduce spesso, in modo naturale, le occasioni per mangiare — e quindi le calorie totali. Per alcune persone questo è più semplice da sostenere rispetto a contare ogni caloria durante l\'intera giornata.' },
      { type: 'quiz', question: 'A parità di calorie totali settimanali, il digiuno intermittente fa perdere più peso di una distribuzione normale dei pasti?', options: ['Sì, in modo significativo', 'No, il risultato è sostanzialmente simile'], correctIndex: 1, explanation: 'Gli studi che confrontano digiuno intermittente e pasti distribuiti normalmente, a parità di calorie totali, mostrano risultati sulla perdita di peso sostanzialmente simili. La differenza è nella sostenibilità individuale, non nella "magia" del metodo.' },
      { type: 'paragraph', text: 'Non è indicato per tutti: chi ha una storia di disturbi alimentari, chi si allena molto presto al mattino, o chi semplicemente non si trova bene a saltare la colazione, può ottenere risultati altrettanto buoni con altri approcci.' },
      { type: 'toolLink', to: '/strumenti/fabbisogno', label: 'Calcola una stima del tuo fabbisogno' },
    ],
  },
  {
    id: 'quante-calorie-piatto-pasta',
    title: 'Quante calorie ha davvero un piatto di pasta',
    excerpt: 'Dipende molto di più dal condimento e dalla porzione che dalla pasta in sé.',
    category: 'Calorie',
    readingTime: 3,
    emoji: '🍝',
    blocks: [
      { type: 'quickAnswer', text: '100 g di pasta di semola cruda apportano circa 353 kcal. Un piatto standard (70-90 g crudi) si aggira quindi sui 250-320 kcal solo di pasta, prima del condimento.' },
      { type: 'paragraph', text: 'Il condimento cambia tutto: un piatto di pasta al pomodoro con un filo d\'olio è molto diverso, dal punto di vista calorico, da uno alla carbonara o con abbondante formaggio. La pasta in sé non è né "leggera" né "pesante": lo diventa in base a cosa ci metti sopra.' },
      { type: 'foodLink', foodId: 'pasta', label: 'Vedi la scheda della pasta di semola' },
      { type: 'quiz', question: 'Una porzione di pasta al pomodoro e una alla carbonara, a parità di grammi di pasta, hanno le stesse calorie totali?', options: ['Sì, circa le stesse', 'No, la carbonara ne ha generalmente molte di più'], correctIndex: 1, explanation: 'Uova, guanciale e formaggio della carbonara aggiungono una quota calorica significativa rispetto a un semplice pomodoro con olio, anche a parità di quantità di pasta.' },
      { type: 'toolLink', to: '/ricette', label: 'Scopri ricette di pasta con valori chiari' },
    ],
  },
  {
    id: 'uova-colesterolo-mito',
    title: 'Le uova alzano davvero il colesterolo?',
    excerpt: 'Uno dei falsi miti più longevi della nutrizione, rivisto alla luce delle ricerche più recenti.',
    category: 'Miti alimentari',
    readingTime: 4,
    emoji: '🥚',
    blocks: [
      { type: 'quickAnswer', text: 'Per la maggior parte delle persone, il colesterolo alimentare (comprese le uova) ha un impatto molto più limitato sul colesterolo nel sangue di quanto si pensasse in passato. Il fegato compensa in gran parte la quota che arriva dal cibo.' },
      { type: 'paragraph', text: 'Per decenni le uova sono state limitate per il loro contenuto di colesterolo. Le linee guida più recenti hanno rivisto questa posizione, dopo che diversi studi non hanno trovato un legame forte tra colesterolo alimentare e rischio cardiovascolare nella popolazione generale.' },
      { type: 'foodLink', foodId: 'uova', label: 'Vedi la scheda dell\'uovo' },
      { type: 'quiz', question: 'Il colesterolo che si trova nel sangue arriva soprattutto dal cibo che mangiamo?', options: ['Sì, soprattutto dal cibo', 'No, il fegato ne produce la maggior parte autonomamente'], correctIndex: 1, explanation: 'Il fegato produce la maggior parte del colesterolo presente nel sangue, indipendentemente da quanto se ne assume con la dieta, e tende a compensarne le variazioni.' },
      { type: 'paragraph', text: 'Esistono comunque situazioni individuali (alcune condizioni genetiche, per esempio) in cui vale la pena parlarne con un professionista: la regola generale non è una garanzia universale.' },
    ],
  },
  {
    id: 'bmi-cosa-dice-davvero',
    title: 'BMI: cosa dice davvero (e cosa no)',
    excerpt: 'Un indicatore utile su scala di popolazione, con limiti reali a livello individuale.',
    category: 'Peso',
    readingTime: 4,
    emoji: '⚖️',
    blocks: [
      { type: 'quickAnswer', text: 'Il BMI (indice di massa corporea) è un rapporto tra peso e altezza, utile per stime rapide su larga scala, ma non distingue tra massa grassa e massa muscolare — quindi va letto con cautela a livello individuale.' },
      { type: 'paragraph', text: 'Il BMI nasce come strumento statistico per studiare popolazioni intere, non per valutare la composizione corporea di una singola persona. Un atleta molto muscoloso può risultare "sovrappeso" secondo il BMI, pur avendo una percentuale di massa grassa molto bassa.' },
      { type: 'toolLink', to: '/strumenti/bmi', label: 'Calcola il tuo BMI' },
      { type: 'quiz', question: 'Il BMI distingue tra massa muscolare e massa grassa?', options: ['Sì, li calcola separatamente', 'No, guarda solo peso e altezza'], correctIndex: 1, explanation: 'Il BMI è un semplice rapporto tra peso e altezza al quadrato: non ha modo di sapere quanto di quel peso sia muscolo, grasso, acqua o osso.' },
      { type: 'paragraph', text: 'Resta comunque un punto di partenza ragionevole per la maggior parte delle persone sedentarie o moderatamente attive: il problema nasce quando lo si usa come unico giudizio, senza contesto.' },
    ],
  },
  {
    id: 'intolleranza-lattosio-cosa-sapere',
    title: 'Intolleranza al lattosio: cosa sapere',
    excerpt: 'Non è un\'allergia, e spesso non significa dover eliminare tutti i latticini.',
    category: 'Intestino',
    readingTime: 4,
    emoji: '🥛',
    blocks: [
      { type: 'quickAnswer', text: 'L\'intolleranza al lattosio è la ridotta capacità di digerire lo zucchero del latte per carenza dell\'enzima lattasi — non un\'allergia, e spesso è una questione di quantità tollerata, non di eliminazione totale.' },
      { type: 'paragraph', text: 'Molte persone intolleranti tollerano comunque piccole quantità di lattosio, o alimenti fermentati come yogurt e kefir, dove parte del lattosio è già stato scomposto dai fermenti durante la lavorazione.' },
      { type: 'foodLink', foodId: 'kefir', label: 'Vedi la scheda del kefir' },
      { type: 'quiz', question: 'Chi è intollerante al lattosio deve necessariamente eliminare del tutto yogurt e formaggi?', options: ['Sì, sempre', 'No, dipende dalla soglia di tolleranza individuale'], correctIndex: 1, explanation: 'La tolleranza al lattosio è spesso una questione di soglia, non di tutto-o-niente: molte persone intolleranti gestiscono bene piccole quantità o alimenti fermentati a basso contenuto di lattosio.' },
      { type: 'paragraph', text: 'In caso di sintomi ricorrenti (gonfiore, crampi, diarrea dopo i latticini), vale la pena parlarne con un professionista prima di eliminare intere categorie di alimenti per conto proprio.' },
    ],
  },
];
