// Ogni articolo è composto da "blocchi" (block-based content), non un
// muro di testo unico. Tipi di blocco: quickAnswer, paragraph, quiz,
// foodLink, toolLink. Questo permette di inserire elementi interattivi
// dentro il flusso dell'articolo, come richiesto dal brief originale.

export const ARTICLES = [
  {
    id: 'quante-calorie-banana',
    title: 'Quante calorie ha davvero una banana?',
    excerpt: 'Un numero semplice, ma che dice più di quanto sembri sulla frutta e sul suo posto nell\'alimentazione.',
    category: 'Calorie',
    readingTime: 4,
    emoji: '🍌',
    blocks: [
      { type: 'quickAnswer', text: 'Una banana media (circa 120 g) contiene circa 107 kcal. Il valore cambia con la dimensione, non con la varietà: più la banana è grande, più kcal apporta, in proporzione diretta.' },
      { type: 'paragraph', text: 'Il numero da solo dice poco. Quello che conta è cosa c\'è dentro quelle calorie: la banana è fatta soprattutto di carboidrati (circa 23 g per 100 g), con una piccola quota di fibre che rallenta l\'assorbimento degli zuccheri naturali.' },
      { type: 'foodLink', foodId: 'banana', label: 'Vedi la scheda completa della banana' },
      { type: 'paragraph', text: 'Il timore diffuso è che "troppo zucchero" nella frutta faccia ingrassare. In realtà il contesto conta più della singola etichetta: una banana non ha lo stesso impatto metabolico di una bibita zuccherata, anche a parità di zuccheri, perché porta con sé fibra, acqua e micronutrienti.' },
      { type: 'quiz', question: 'Quante kcal pensi abbiano 100 g di mandorle?', options: ['320 kcal', '450 kcal', '579 kcal'], correctIndex: 2, explanation: 'Le mandorle sono un alimento molto energetico: 579 kcal per 100 g, quasi 6,5 volte quelle della banana. Non "cattive": semplicemente molto dense, quindi la porzione conta più che mai.' },
      { type: 'paragraph', text: 'Ecco perché confrontare due alimenti solo per le kcal totali, senza guardare la porzione reale che si mangia, porta spesso a conclusioni sbagliate.' },
      { type: 'toolLink', to: '/confronta?a=banana', label: 'Confronta la banana con un altro alimento' },
    ],
  },
  {
    id: 'deficit-calorico',
    title: 'Come funziona davvero il deficit calorico',
    excerpt: 'Il concetto più citato (e più frainteso) quando si parla di perdita di peso.',
    category: 'Dimagrimento',
    readingTime: 5,
    emoji: '🔥',
    blocks: [
      { type: 'quickAnswer', text: 'Il deficit calorico significa consumare meno energia di quella che il corpo utilizza in un giorno. È il meccanismo alla base della perdita di peso, indipendentemente dal tipo di dieta seguita.' },
      { type: 'paragraph', text: 'Il tuo corpo brucia energia anche da fermo, per mantenere le funzioni vitali: è il metabolismo basale. A questo si aggiunge l\'energia spesa muovendosi durante la giornata e allenandosi. La somma di tutto è il tuo "fabbisogno di mantenimento".' },
      { type: 'toolLink', to: '/strumenti/fabbisogno', label: 'Calcola una stima del tuo fabbisogno' },
      { type: 'paragraph', text: 'Un deficit moderato (circa 300-500 kcal sotto il mantenimento) è generalmente più sostenibile nel tempo rispetto a un deficit drastico, che tende a portare a fame eccessiva e difficoltà a mantenere il percorso nel lungo periodo.' },
      { type: 'quiz', question: 'Saltare completamente un pasto per aumentare il deficit è generalmente una strategia sostenibile?', options: ['Sì, più deficit è sempre meglio', 'No, spesso porta a fame eccessiva dopo'], correctIndex: 1, explanation: 'Un deficit troppo aggressivo o pasti saltati spesso portano a una fame che si "ripaga" nei pasti successivi, rendendo il percorso più difficile da mantenere nel tempo.' },
      { type: 'paragraph', text: 'Il deficit calorico è un principio, non una ricetta: come raggiungerlo (quali alimenti, quanti pasti, quale distribuzione) dipende dalla situazione di ciascuno.' },
    ],
  },
  {
    id: 'quante-proteine-servono',
    title: 'Quante proteine servono davvero?',
    excerpt: 'Un intervallo, non un numero magico: dipende da peso e livello di attività.',
    category: 'Proteine',
    readingTime: 4,
    emoji: '💪',
    blocks: [
      { type: 'quickAnswer', text: 'Non esiste un numero unico valido per tutti: l\'intervallo indicativo va da circa 0,8 g per kg di peso corporeo (sedentari) fino a 2,2 g/kg per chi si allena intensamente.' },
      { type: 'paragraph', text: 'Le proteine servono soprattutto per il mantenimento e la costruzione della massa muscolare, ma anche per moltissime altre funzioni dell\'organismo. L\'idea che "più proteine mangi, più muscoli metti su" è una semplificazione: senza un adeguato stimolo allenante, l\'eccesso proteico non si trasforma automaticamente in muscolo.' },
      { type: 'toolLink', to: '/strumenti/proteine', label: 'Calcola il tuo intervallo indicativo' },
      { type: 'quiz', question: 'Un alimento con molte proteine viene automaticamente convertito in massa muscolare?', options: ['Sì, in proporzione diretta', 'No, serve anche un adeguato allenamento'], correctIndex: 1, explanation: 'La sintesi proteica muscolare richiede uno stimolo allenante (di solito di resistenza) oltre a un apporto proteico adeguato. Mangiare più proteine da solo non basta.' },
      { type: 'paragraph', text: 'Alcuni alimenti particolarmente proteici, per farsi un\'idea: petto di pollo, tonno, uova, albume, yogurt greco, legumi, tofu e tempeh.' },
      { type: 'foodLink', foodId: 'pollo', label: 'Vedi la scheda del petto di pollo' },
    ],
  },
  {
    id: 'carboidrati-sera',
    title: 'Carboidrati la sera: fanno ingrassare?',
    excerpt: 'Uno dei falsi miti più diffusi sull\'alimentazione, messo alla prova.',
    category: 'Metabolismo',
    readingTime: 3,
    emoji: '🌙',
    blocks: [
      { type: 'quickAnswer', text: 'No: l\'aumento di peso dipende dal bilancio calorico complessivo della giornata (o della settimana), non dall\'orario in cui si mangiano i carboidrati.' },
      { type: 'paragraph', text: 'L\'idea che il corpo "processi" i carboidrati in modo diverso la sera rispetto al mattino non trova conferma solida: quello che conta è quante calorie totali si assumono rispetto a quante se ne consumano, indipendentemente dalla distribuzione oraria dei pasti.' },
      { type: 'quiz', question: 'Mangiare pasta a cena invece che a pranzo, a parità di calorie totali della giornata, cambia il risultato sul peso?', options: ['Sì, significativamente', 'No, non in modo significativo'], correctIndex: 1, explanation: 'A parità di bilancio calorico complessivo, l\'orario del pasto non è il fattore determinante. Contano di più le abitudini sostenibili nel tempo.' },
      { type: 'paragraph', text: 'Questo non significa che l\'orario dei pasti non conti mai per nessuno (ad esempio per chi soffre di reflusso, o per chi si allena la mattina presto): significa solo che non esiste una regola universale "carboidrati vietati dopo una certa ora".' },
      { type: 'toolLink', to: '/mito-o-verita', label: 'Metti alla prova altri falsi miti' },
    ],
  },
  {
    id: 'cosa-mangiare-prima-allenamento',
    title: 'Cosa mangiare prima di allenarsi',
    excerpt: 'Timing, quantità e qualche errore comune prima di un allenamento.',
    category: 'Sport',
    readingTime: 4,
    emoji: '🏋️',
    blocks: [
      { type: 'quickAnswer', text: 'Un pasto con carboidrati e una quota moderata di proteine, consumato 1-3 ore prima dell\'allenamento, è generalmente una buona base. Più vicino sei all\'allenamento, più il pasto dovrebbe essere leggero e digeribile.' },
      { type: 'paragraph', text: 'I carboidrati forniscono energia rapidamente disponibile per il muscolo. Le proteine, in quantità moderata, non sono indispensabili prima dell\'allenamento (contano di più nell\'arco della giornata), ma non creano problemi se ben tollerate.' },
      { type: 'foodLink', foodId: 'riso', label: 'Vedi la scheda del riso basmati' },
      { type: 'quiz', question: 'Un pasto molto ricco di grassi appena prima di allenarsi è generalmente una buona idea?', options: ['Sì, dà energia extra', 'No, rallenta la digestione ed è scomodo durante lo sforzo'], correctIndex: 1, explanation: 'I grassi rallentano la digestione: un pasto pesante e grasso subito prima di allenarsi può causare pesantezza o disagio durante lo sforzo.' },
      { type: 'paragraph', text: 'Non esiste un\'unica combinazione valida per tutti: il modo migliore per capire cosa funziona è osservare come si sente il proprio corpo con pasti diversi, a distanze diverse dall\'allenamento.' },
    ],
  },
  {
    id: 'fibre-salute-intestinale',
    title: 'Le fibre e la salute intestinale',
    excerpt: 'Perché le fibre non servono solo a "regolarizzare", ma nutrono anche i batteri intestinali.',
    category: 'Intestino',
    readingTime: 4,
    emoji: '🌾',
    blocks: [
      { type: 'quickAnswer', text: 'Le fibre non vengono digerite dal nostro intestino, ma sono il "cibo" dei batteri intestinali, che le fermentano producendo sostanze utili per la salute della mucosa intestinale.' },
      { type: 'paragraph', text: 'Legumi, cereali integrali, verdura e frutta sono le fonti principali di fibra nella dieta. Aumentarne gradualmente il consumo (non di colpo, per evitare gonfiore) è generalmente associato a una buona regolarità intestinale.' },
      { type: 'foodLink', foodId: 'lenticchie', label: 'Vedi la scheda delle lenticchie' },
      { type: 'quiz', question: 'Tra questi due, quale contiene più fibre per 100 g?', options: ['Lenticchie cotte (7,9 g)', 'Riso basmati (1 g)'], correctIndex: 0, explanation: 'I legumi come le lenticchie sono tra le fonti di fibra più concentrate tra gli alimenti comuni, molto più dei cereali raffinati come il riso bianco.' },
      { type: 'toolLink', to: '/ricette', label: 'Scopri ricette ricche di fibre' },
    ],
  },
  {
    id: 'dieta-chetogenica-come-funziona',
    title: 'Dieta chetogenica: come funziona davvero',
    excerpt: 'Il meccanismo dietro il regime low-carb più discusso, senza semplificazioni.',
    category: 'Keto & Low Carb',
    readingTime: 5,
    emoji: '🥑',
    blocks: [
      { type: 'quickAnswer', text: 'La dieta chetogenica riduce drasticamente i carboidrati (di solito sotto i 50 g al giorno), spingendo il corpo a produrre "corpi chetonici" dai grassi come fonte di energia alternativa al glucosio.' },
      { type: 'paragraph', text: 'Questo cambiamento metabolico si chiama chetosi. Non è un interruttore magico per il dimagrimento: la perdita di peso avviene comunque tramite un deficit calorico, che in un regime chetogenico è spesso più facile da ottenere per l\'effetto saziante di grassi e proteine.' },
      { type: 'quiz', question: 'La chetosi è di per sé indispensabile per perdere peso?', options: ['Sì, senza chetosi non si dimagrisce', 'No, il deficit calorico è il fattore determinante, con o senza chetosi'], correctIndex: 1, explanation: 'Si può perdere peso con qualsiasi approccio alimentare che porti a un deficit calorico sostenuto nel tempo. La chetosi è un meccanismo, non l\'unica via.' },
      { type: 'toolLink', to: '/strumenti/fabbisogno', label: 'Calcola una stima del tuo fabbisogno' },
      { type: 'paragraph', text: 'Un regime così restrittivo sui carboidrati non è adatto o piacevole per tutti: la sostenibilità nel tempo conta quanto il meccanismo biologico.' },
    ],
  },
  {
    id: 'mito-metabolismo-lento',
    title: 'Il mito del "metabolismo lento"',
    excerpt: 'Quanto conta davvero il metabolismo basale nella storia del peso corporeo.',
    category: 'Miti alimentari',
    readingTime: 4,
    emoji: '🐢',
    blocks: [
      { type: 'quickAnswer', text: 'Le differenze di metabolismo basale tra persone della stessa età, peso e altezza esistono, ma sono generalmente molto più piccole di quanto si creda comunemente — raramente bastano da sole a spiegare grandi differenze di peso.' },
      { type: 'paragraph', text: '"Ho un metabolismo lento" è spesso usato per spiegare la difficoltà a perdere peso, ma il dispendio energetico totale dipende da molti fattori: massa muscolare, livello di attività quotidiana (non solo l\'allenamento strutturato), e le dimensioni corporee stesse.' },
      { type: 'quiz', question: 'A parità di peso e altezza, due persone hanno sempre un metabolismo basale molto diverso tra loro?', options: ['Sì, le differenze sono enormi', 'No, le differenze sono generalmente contenute'], correctIndex: 1, explanation: 'Le variazioni individuali esistono, ma la ricerca mostra che sono più contenute di quanto la percezione comune suggerisca. Il comportamento quotidiano pesa di più.' },
      { type: 'toolLink', to: '/mito-o-verita', label: 'Metti alla prova altri falsi miti' },
    ],
  },
];
