import { FOODS, calc } from './foods';

export const RECIPES = [
  {
    id: 'pasta-tonno-pomodoro',
    name: 'Pasta al tonno e pomodoro',
    emoji: '🍝',
    description: 'Un piatto veloce e proteico, pronto in 15 minuti con pochi ingredienti.',
    category: 'Pranzo',
    tags: ['proteico', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pasta', grams: 80 },
      { foodId: 'tonno', grams: 100 },
      { foodId: 'pomodoro', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Porta a bollore l\'acqua e cuoci la pasta secondo i tempi indicati sulla confezione.',
      'Nel frattempo scalda l\'olio in padella e aggiungi il pomodoro tagliato a pezzi.',
      'Aggiungi il tonno sgocciolato e scalda per 2-3 minuti.',
      'Scola la pasta e saltala in padella con il condimento per un minuto.',
    ],
  },
  {
    id: 'toast-avocado-uovo',
    name: 'Toast con avocado e uovo',
    emoji: '🥑',
    description: 'Colazione salata bilanciata tra grassi buoni e proteine.',
    category: 'Colazione',
    tags: ['vegetariano', 'veloce'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pane', grams: 60 },
      { foodId: 'avocado', grams: 70 },
      { foodId: 'uova', grams: 100 },
    ],
    steps: [
      'Tosta le fette di pane integrale.',
      'Schiaccia l\'avocado con una forchetta e distribuiscilo sul pane.',
      'Cuoci l\'uovo come preferisci (in camicia, sodo o strapazzato) e adagialo sopra.',
    ],
  },
  {
    id: 'pollo-riso-spinaci',
    name: 'Pollo, riso e spinaci',
    emoji: '🍗',
    description: 'Il classico piatto post-allenamento: semplice, completo, senza sorprese.',
    category: 'Cena',
    tags: ['proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pollo', grams: 150 },
      { foodId: 'riso', grams: 80 },
      { foodId: 'spinaci', grams: 100 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Cuoci il petto di pollo in padella o al forno fino a completa cottura.',
      'Salta velocemente gli spinaci in padella con un filo d\'olio.',
      'Componi il piatto con riso, pollo a fette e spinaci.',
    ],
  },
  {
    id: 'yogurt-banana-mandorle',
    name: 'Yogurt, banana e mandorle',
    emoji: '🥣',
    description: 'Uno snack o una colazione pronta in cinque minuti, senza cottura.',
    category: 'Colazione',
    tags: ['vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'yogurt', grams: 150 },
      { foodId: 'banana', grams: 100 },
      { foodId: 'mandorle', grams: 15 },
    ],
    steps: [
      'Versa lo yogurt greco in una ciotola.',
      'Taglia la banana a rondelle e aggiungila.',
      'Completa con le mandorle, intere o tritate grossolanamente.',
    ],
  },
  {
    id: 'insalata-mediterranea',
    name: 'Insalata mediterranea con tonno',
    emoji: '🥗',
    description: 'Fresca, leggera, perfetta per un pranzo estivo o una cena veloce.',
    category: 'Pranzo',
    tags: ['leggero', 'veloce'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pomodoro', grams: 200 },
      { foodId: 'tonno', grams: 80 },
      { foodId: 'olio', grams: 10 },
      { foodId: 'pane', grams: 40 },
    ],
    steps: [
      'Taglia il pomodoro a spicchi e disponilo in una ciotola.',
      'Aggiungi il tonno sgocciolato.',
      'Condisci con l\'olio EVO.',
      'Servi con il pane a fette, tostato o a crostini.',
    ],
  },
  {
    id: 'buddha-bowl-quinoa-ceci',
    name: 'Buddha bowl con quinoa e ceci',
    emoji: '🥗',
    description: 'Una ciotola completa, colorata e completamente vegetale.',
    category: 'Pranzo',
    tags: ['vegano', 'vegetariano', 'proteico'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'quinoa', grams: 80 },
      { foodId: 'ceci', grams: 100 },
      { foodId: 'avocado', grams: 50 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci la quinoa secondo i tempi indicati sulla confezione.',
      'Scola i ceci se in barattolo, oppure scaldali se già cotti.',
      'Componi la bowl con quinoa, ceci, avocado a fette e pomodoro a cubetti.',
      'Condisci con un filo d\'olio EVO.',
    ],
  },
  {
    id: 'salmone-forno-patate',
    name: 'Salmone al forno con patate',
    emoji: '🐟',
    description: 'Un secondo completo, ricco di omega-3 e facile da preparare.',
    category: 'Cena',
    tags: ['proteico'],
    time: 30,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'salmone', grams: 150 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'spinaci', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a tocchetti e cuocile in forno a 200°C per circa 25 minuti.',
      'Inforna il salmone condito con un filo d\'olio per gli ultimi 15 minuti.',
      'Salta velocemente gli spinaci in padella con un filo d\'olio.',
      'Componi il piatto con salmone, patate e spinaci.',
    ],
  },
  {
    id: 'tofu-saltato-verdure',
    name: 'Tofu saltato con verdure',
    emoji: '🧊',
    description: 'Veloce, leggero, completamente vegetale.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tofu', grams: 150 },
      { foodId: 'zucchine', grams: 150 },
      { foodId: 'carote', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia il tofu a cubetti e rosolalo in padella con un filo d\'olio finché non è dorato.',
      'Aggiungi le verdure tagliate a listarelle sottili.',
      'Salta tutto insieme per 8-10 minuti a fuoco medio-alto.',
    ],
  },
  {
    id: 'farro-mozzarella-pomodoro',
    name: 'Insalata di farro con mozzarella e pomodoro',
    emoji: '🥣',
    description: 'Fresca e sazia, perfetta anche portata fuori casa.',
    category: 'Pranzo',
    tags: ['vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farro', grams: 100 },
      { foodId: 'mozzarella', grams: 100 },
      { foodId: 'pomodoro', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il farro e lascialo raffreddare.',
      'Taglia la mozzarella a cubetti e il pomodoro a pezzi.',
      'Unisci tutto e condisci con olio EVO, sale e origano a piacere.',
    ],
  },
  {
    id: 'porridge-avena-mirtilli',
    name: 'Porridge di avena con mirtilli e mandorle',
    emoji: '🥣',
    description: 'Colazione calda, sazia a lungo grazie alle fibre dell\'avena.',
    category: 'Colazione',
    tags: ['vegetariano', 'veloce'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 50 },
      { foodId: 'latte-scremato', grams: 200 },
      { foodId: 'mirtilli', grams: 50 },
      { foodId: 'mandorle', grams: 10 },
    ],
    steps: [
      'Cuoci l\'avena nel latte a fuoco basso per circa 5 minuti, mescolando spesso.',
      'Versa in una ciotola.',
      'Completa con mirtilli freschi e mandorle.',
    ],
  },
  {
    id: 'seitan-piastra-verdure',
    name: 'Seitan alla piastra con verdure miste',
    emoji: '🌾',
    description: 'Un secondo vegetale ricco di proteine, pronto in venti minuti.',
    category: 'Cena',
    tags: ['vegano', 'vegetariano', 'proteico'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'seitan', grams: 150 },
      { foodId: 'zucchine', grams: 100 },
      { foodId: 'peperoni', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia il seitan a fette non troppo sottili.',
      'Cuocilo alla piastra 3-4 minuti per lato.',
      'Nel frattempo salta le verdure in padella con un filo d\'olio.',
      'Servi il seitan con le verdure a fianco.',
    ],
  },
  {
    id: 'lenticchie-stufate',
    name: 'Lenticchie stufate',
    emoji: '🫘',
    description: 'Un classico confortante, ricco di fibre e proteine vegetali.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'lenticchie', grams: 200 },
      { foodId: 'cipolla', grams: 50 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Soffriggi la cipolla tritata nell\'olio finché non appassisce.',
      'Aggiungi il pomodoro a pezzi e cuoci 5 minuti.',
      'Unisci le lenticchie già cotte e scalda insieme per altri 5 minuti.',
    ],
  },
  {
    id: 'smoothie-proteico-banana',
    name: 'Smoothie proteico alla banana',
    emoji: '🥤',
    description: 'Pronto in cinque minuti, comodo dopo l\'allenamento.',
    category: 'Snack',
    tags: ['proteico', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'banana', grams: 100 },
      { foodId: 'proteine-isolate', grams: 30 },
      { foodId: 'latte-scremato', grams: 200 },
    ],
    steps: [
      'Metti tutti gli ingredienti nel frullatore.',
      'Frulla fino a ottenere una consistenza liscia e omogenea.',
      'Servi subito.',
    ],
  },
  {
    id: 'pancake-avena-albume',
    name: 'Pancake proteici con farina d\'avena e albume',
    emoji: '🥞',
    description: 'Colazione o post-allenamento, ricca di proteine e senza zuccheri aggiunti.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 40 },
      { foodId: 'albume', grams: 120 },
      { foodId: 'banana', grams: 50 },
    ],
    steps: [
      'Frulla l\'avena fino a ottenere una farina fine.',
      'Schiaccia la banana e uniscila alla farina d\'avena e all\'albume, mescolando fino a ottenere un composto omogeneo.',
      'Cuoci piccole porzioni di composto in una padella antiaderente calda, 2-3 minuti per lato.',
    ],
  },
  {
    id: 'porridge-proteico-frutta-yogurt',
    name: 'Porridge proteico con frutta e yogurt greco',
    emoji: '🥣',
    description: 'Avena cotta nel latte proteico, completata con yogurt greco e frutta fresca.',
    category: 'Colazione',
    tags: ['proteico'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 50 },
      { foodId: 'latte-proteico', grams: 200 },
      { foodId: 'yogurt-greco-0', grams: 80 },
      { foodId: 'mirtilli', grams: 50 },
    ],
    steps: [
      'Cuoci l\'avena nel latte proteico a fuoco basso per circa 5 minuti, mescolando spesso.',
      'Versa in una ciotola e lascia intiepidire un paio di minuti.',
      'Completa con lo yogurt greco e i mirtilli freschi.',
    ],
  },
  {
    id: 'frittata-albumi-spinaci',
    name: 'Frittata di albumi con spinaci',
    emoji: '🍳',
    description: 'Molte proteine, pochissimi grassi: un classico da palestra.',
    category: 'Colazione/Pranzo',
    tags: ['proteico', 'leggero', 'veloce'],
    time: 12,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'albume', grams: 200 },
      { foodId: 'spinaci', grams: 100 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Salta velocemente gli spinaci in padella con un filo d\'olio finché non appassiscono.',
      'Versa gli albumi sopra gli spinaci nella stessa padella.',
      'Cuoci a fuoco medio-basso, muovendo leggermente i bordi, finché non si rapprendono del tutto.',
    ],
  },
  {
    id: 'pollo-patate-broccoli-forno',
    name: 'Pollo, patate e broccoli al forno',
    emoji: '🍗',
    description: 'Il pasto da palestra per eccellenza: semplice, prevedibile, efficace.',
    category: 'Pranzo/Cena',
    tags: ['proteico'],
    time: 35,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'pollo', grams: 180 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'broccoli', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a tocchetti e disponile su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Aggiungi il pollo a pezzi e i broccoli, e continua la cottura per altri 15 minuti.',
    ],
  },
  {
    id: 'riso-tonno-piselli',
    name: 'Riso con tonno e piselli',
    emoji: '🍚',
    description: 'Pratico da preparare in anticipo, ottimo dopo l\'allenamento.',
    category: 'Pranzo',
    tags: ['proteico', 'veloce', 'post-workout'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'riso', grams: 100 },
      { foodId: 'tonno', grams: 100 },
      { foodId: 'piselli', grams: 80 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata.',
      'Scalda i piselli in padella con un filo d\'olio.',
      'Scola il riso, unisci il tonno sgocciolato e i piselli, mescola e servi.',
    ],
  },
  {
    id: 'overnight-oats-proteici',
    name: 'Overnight oats proteici',
    emoji: '🌙',
    description: 'Prepari la sera prima, la mattina è già pronta: perfetta per chi ha poco tempo.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 50 },
      { foodId: 'yogurt-greco-2', grams: 100 },
      { foodId: 'latte-proteico', grams: 100 },
      { foodId: 'mirtilli', grams: 50 },
    ],
    steps: [
      'Mescola avena, yogurt greco e latte proteico in un barattolo con coperchio.',
      'Aggiungi i mirtilli, chiudi e lascia riposare in frigorifero per almeno 6 ore, meglio tutta la notte.',
      'Al mattino mescola bene prima di mangiare, aggiungendo altro latte se troppo denso.',
    ],
  },
  {
    id: 'tacchino-riso-integrale-zucchine',
    name: 'Tacchino con riso integrale e zucchine',
    emoji: '🍗',
    description: 'Magro, leggero, facile da preparare in più porzioni per la settimana.',
    category: 'Cena',
    tags: ['proteico', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tacchino', grams: 180 },
      { foodId: 'riso-integrale', grams: 150 },
      { foodId: 'zucchine', grams: 150 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso integrale secondo i tempi indicati sulla confezione.',
      'Cuoci la fesa di tacchino in padella a fuoco medio, 4-5 minuti per lato.',
      'Salta le zucchine a rondelle in padella con un filo d\'olio.',
      'Componi il piatto con riso, tacchino a fette e zucchine.',
    ],
  },
  {
    id: 'merluzzo-patate-finocchi',
    name: 'Merluzzo al forno con patate e finocchi',
    emoji: '🐟',
    description: 'Un secondo leggero e delicato, cotto tutto insieme in forno.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 35,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'merluzzo', grams: 180 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'finocchi', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia patate e finocchi a fette sottili e disponili su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Aggiungi il merluzzo condito con un filo d\'olio e continua la cottura per altri 12-15 minuti.',
    ],
  },
  {
    id: 'gamberi-couscous-zucchine',
    name: 'Gamberi saltati con couscous e zucchine',
    emoji: '🦐',
    description: 'Un piatto unico dal sapore fresco, pronto in mezz\'ora.',
    category: 'Pranzo/Cena',
    tags: ['leggero', 'veloce'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'gamberi', grams: 180 },
      { foodId: 'couscous', grams: 80 },
      { foodId: 'zucchine', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Prepara il couscous seguendo le indicazioni sulla confezione.',
      'Taglia le zucchine a cubetti e saltale in padella con un filo d\'olio per 5-6 minuti.',
      'Aggiungi i gamberi e cuoci ancora 3-4 minuti, finché non diventano rosati.',
      'Componi il piatto con il couscous come base, gamberi e zucchine sopra.',
    ],
  },
  {
    id: 'farro-ceci-verdure',
    name: 'Farro con ceci e verdure miste',
    emoji: '🥣',
    description: 'Un piatto completamente vegetale, sazio grazie a fibre e legumi.',
    category: 'Pranzo',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farro', grams: 90 },
      { foodId: 'ceci', grams: 120 },
      { foodId: 'zucchine', grams: 100 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il farro secondo i tempi indicati sulla confezione e lascialo intiepidire.',
      'Salta le zucchine a cubetti in padella con un filo d\'olio per 5 minuti.',
      'Unisci il farro, i ceci e il pomodoro a pezzi.',
      'Mescola bene e condisci con un filo d\'olio a crudo.',
    ],
  },
  {
    id: 'melanzane-gratinate-pomodoro-mozzarella',
    name: 'Melanzane gratinate con pomodoro e mozzarella',
    emoji: '🍆',
    description: 'Una versione più semplice e veloce di un grande classico.',
    category: 'Cena',
    tags: ['vegetariano'],
    time: 35,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'melanzane', grams: 250 },
      { foodId: 'pomodoro', grams: 150 },
      { foodId: 'mozzarella', grams: 100 },
      { foodId: 'parmigiano', grams: 15 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le melanzane a fette e grigliale in padella o su una piastra finché non sono morbide.',
      'Disponi le melanzane a strati in una teglia, alternando con pomodoro a pezzi e mozzarella.',
      'Completa con parmigiano grattugiato e un filo d\'olio.',
      'Cuoci in forno a 200°C per 15-18 minuti, finché la superficie non è dorata.',
    ],
  },
  {
    id: 'orzo-verdure-mozzarella',
    name: 'Insalata di orzo con verdure e mozzarella',
    emoji: '🥗',
    description: 'Fresca e pratica, ottima anche preparata in anticipo.',
    category: 'Pranzo',
    tags: ['vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'orzo', grams: 90 },
      { foodId: 'pomodoro', grams: 120 },
      { foodId: 'peperoni', grams: 80 },
      { foodId: 'mozzarella', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci l\'orzo in acqua bollente salata secondo i tempi indicati, poi scolalo e lascialo raffreddare.',
      'Taglia pomodoro, peperoni e mozzarella a cubetti.',
      'Unisci tutto all\'orzo e condisci con un filo d\'olio.',
    ],
  },
  {
    id: 'manzo-patate-broccoli-forno',
    name: 'Manzo con patate e broccoli al forno',
    emoji: '🥩',
    description: 'Un secondo sostanzioso, cotto interamente al forno in un\'unica teglia.',
    category: 'Cena',
    tags: ['proteico'],
    time: 35,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'manzo', grams: 180 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'broccoli', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a tocchetti e disponile su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Aggiungi il manzo a fette e i broccoli, e continua la cottura per altri 15 minuti.',
    ],
  },
  {
    id: 'riso-edamame-verdure-saltate',
    name: 'Riso con edamame e verdure saltate',
    emoji: '🍚',
    description: 'Piatto unico vegetale ispirato alla cucina asiatica, pronto in 20 minuti.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'veloce'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'riso', grams: 90 },
      { foodId: 'edamame', grams: 100 },
      { foodId: 'carote', grams: 80 },
      { foodId: 'peperoni', grams: 80 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Taglia carote e peperoni a listarelle sottili e saltali in padella con un filo d\'olio per 5-6 minuti.',
      'Aggiungi gli edamame già scottati e scalda insieme per 2-3 minuti.',
      'Unisci il riso scolato e mescola bene prima di servire.',
    ],
  },
  {
    id: 'sgombro-finocchi-arancia',
    name: 'Sgombro con insalata di finocchi e arancia',
    emoji: '🐟',
    description: 'Un abbinamento fresco tra pesce azzurro e note agrumate.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'sgombro', grams: 150 },
      { foodId: 'finocchi', grams: 150 },
      { foodId: 'arancia', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci lo sgombro in padella o al forno finché non è cotto.',
      'Affetta finemente i finocchi e l\'arancia a spicchi.',
      'Componi l\'insalata con finocchi e arancia, condita con un filo d\'olio.',
      'Servi lo sgombro accanto all\'insalata.',
    ],
  },
  {
    id: 'fagioli-umido-pane-integrale',
    name: 'Fagioli in umido con pane integrale',
    emoji: '🫘',
    description: 'Un piatto povero solo nel nome: sazio, economico e ricco di fibre.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'fagioli', grams: 200 },
      { foodId: 'cipolla', grams: 50 },
      { foodId: 'pomodoro', grams: 120 },
      { foodId: 'pane', grams: 60 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Soffriggi la cipolla tritata nell\'olio finché non appassisce.',
      'Aggiungi il pomodoro a pezzi e cuoci per 5 minuti.',
      'Unisci i fagioli già cotti e lascia insaporire per altri 8-10 minuti a fuoco basso.',
      'Servi con il pane integrale a fette.',
    ],
  },
  {
    id: 'sogliola-limone-patate-dolci',
    name: 'Sogliola al limone con patate dolci al forno',
    emoji: '🐟',
    description: 'Un secondo delicato, pronto in mezz\'ora, con un contorno dal gusto leggermente dolce.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 30,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'sogliola', grams: 180 },
      { foodId: 'patate-dolci', grams: 200 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate dolci a spicchi e disponile su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Cuoci la sogliola in padella con un filo d\'olio per 3-4 minuti per lato, poi completa con succo di limone.',
    ],
  },
  {
    id: 'nasello-funghi-patate',
    name: 'Nasello con funghi trifolati e patate',
    emoji: '🐟',
    description: 'Un piatto classico e confortante, con il sapore terroso dei funghi.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 30,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'nasello', grams: 180 },
      { foodId: 'funghi', grams: 150 },
      { foodId: 'patate', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Lessa le patate a tocchetti finché non sono morbide.',
      'Salta i funghi affettati in padella con un filo d\'olio per 6-7 minuti.',
      'Cuoci il nasello a vapore o in padella per 6-8 minuti e servi con funghi e patate.',
    ],
  },
  {
    id: 'calamari-couscous-hummus',
    name: 'Calamari saltati con couscous e hummus',
    emoji: '🦑',
    description: 'Un piatto unico dai sapori mediterranei, con una crema di ceci a legare il tutto.',
    category: 'Pranzo/Cena',
    tags: ['proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'calamaro', grams: 180 },
      { foodId: 'couscous', grams: 70 },
      { foodId: 'hummus', grams: 60 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Prepara il couscous seguendo le indicazioni sulla confezione.',
      'Taglia i calamari ad anelli e saltali in padella con un filo d\'olio per 3-4 minuti a fuoco vivo.',
      'Componi il piatto con il couscous, i calamari sopra e una cucchiaiata di hummus a lato.',
    ],
  },
  {
    id: 'polpo-patate-pomodorini',
    name: 'Polpo con patate e pomodorini',
    emoji: '🐙',
    description: 'Un grande classico della cucina di mare, qui in versione semplificata.',
    category: 'Pranzo/Cena',
    tags: ['proteico'],
    time: 40,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'polpo', grams: 200 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Lessa il polpo in acqua bollente finché non è tenero (i tempi variano parecchio in base alla pezzatura: verifica con una forchetta).',
      'Lessa le patate a tocchetti finché non sono morbide.',
      'Taglia il polpo a pezzi, unisci le patate e i pomodorini tagliati a metà.',
      'Condisci con un filo d\'olio a crudo.',
    ],
  },
  {
    id: 'cefalo-finocchi-arancia',
    name: 'Cefalo alla griglia con insalata di finocchi e arancia',
    emoji: '🐟',
    description: 'Un secondo fresco, con un contorno agrumato che sgrassa il palato.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'cefalo', grams: 180 },
      { foodId: 'finocchi', grams: 150 },
      { foodId: 'arancia', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il cefalo alla griglia o in padella per 4-5 minuti per lato.',
      'Affetta finemente finocchi e arancia a spicchi.',
      'Componi l\'insalata condendola con un filo d\'olio e servila accanto al pesce.',
    ],
  },
  {
    id: 'rombo-forno-patate',
    name: 'Rombo al forno con patate',
    emoji: '🐟',
    description: 'Cottura unica in teglia, per un secondo delicato senza troppi passaggi.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 35,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'rombo', grams: 200 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a fette sottili e disponile su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 15 minuti.',
      'Aggiungi il rombo condito con un filo d\'olio e continua la cottura per altri 15-18 minuti.',
    ],
  },
  {
    id: 'orata-forno-patate-finocchi',
    name: 'Orata al forno con patate e finocchi',
    emoji: '🐟',
    description: 'Un secondo tutto in teglia, con finocchi che profumano la cottura.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 35,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'orata', grams: 220 },
      { foodId: 'patate', grams: 180 },
      { foodId: 'finocchi', grams: 120 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia patate e finocchi a fette sottili e disponili su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 15 minuti.',
      'Aggiungi l\'orata condita con un filo d\'olio e continua la cottura per altri 18-20 minuti.',
    ],
  },
  {
    id: 'spigola-vapore-riso-verdure',
    name: 'Spigola al vapore con riso e verdure',
    emoji: '🐟',
    description: 'Un piatto unico leggero, cotto quasi interamente al vapore.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'spigola', grams: 200 },
      { foodId: 'riso', grams: 80 },
      { foodId: 'zucchine', grams: 120 },
      { foodId: 'carote', grams: 80 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Cuoci la spigola e le verdure a vapore per 10-12 minuti.',
      'Componi il piatto con il riso come base, spigola e verdure sopra, condito con un filo d\'olio.',
    ],
  },
  {
    id: 'cornflakes-kefir-frutti-bosco',
    name: 'Cornflakes con kefir e frutti di bosco',
    emoji: '🌽',
    description: 'Colazione veloce e fresca, pronta in due minuti.',
    category: 'Colazione',
    tags: ['veloce', 'vegetariano'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'cornflakes-mais', grams: 40 },
      { foodId: 'kefir', grams: 200 },
      { foodId: 'mirtilli', grams: 80 },
    ],
    steps: [
      'Versa i cornflakes in una ciotola.',
      'Aggiungi il kefir e mescola.',
      'Completa con i mirtilli.',
    ],
  },
  {
    id: 'muesli-yogurt-greco-mirtilli',
    name: 'Muesli con yogurt greco e mirtilli',
    emoji: '🥣',
    description: 'Una colazione più sostanziosa, con la cremosità dello yogurt greco.',
    category: 'Colazione',
    tags: ['veloce', 'vegetariano', 'proteico'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'muesli', grams: 50 },
      { foodId: 'yogurt-greco-0', grams: 170 },
      { foodId: 'mirtilli', grams: 80 },
    ],
    steps: [
      'Versa lo yogurt greco in una ciotola.',
      'Aggiungi il muesli e mescola.',
      'Completa con i mirtilli.',
    ],
  },
  {
    id: 'toast-philadelphia-salmone-cetriolo',
    name: 'Toast con Philadelphia light, salmone affumicato e cetriolo',
    emoji: '🥪',
    description: 'Un classico da brunch, pronto in pochi minuti.',
    category: 'Colazione/Pranzo',
    tags: ['veloce', 'proteico'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pane', grams: 80 },
      { foodId: 'philadelphia-light', grams: 40 },
      { foodId: 'salmone-affumicato', grams: 60 },
      { foodId: 'cetrioli', grams: 50 },
    ],
    steps: [
      'Tosta le fette di pane.',
      'Spalma il Philadelphia light su ogni fetta.',
      'Aggiungi il salmone affumicato e qualche fetta sottile di cetriolo.',
    ],
  },
  {
    id: 'fiocchi-latte-banana-mandorle',
    name: 'Fiocchi di latte con banana e mandorle',
    emoji: '🧀',
    description: 'Uno spuntino proteico e saziante, pronto in un minuto.',
    category: 'Snack',
    tags: ['veloce', 'vegetariano', 'proteico'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'fiocchi-latte-0', grams: 150 },
      { foodId: 'banana', grams: 100 },
      { foodId: 'mandorle', grams: 15 },
    ],
    steps: [
      'Versa i fiocchi di latte in una ciotola.',
      'Aggiungi la banana a fette.',
      'Completa con le mandorle.',
    ],
  },
  {
    id: 'riso-soffiato-latte-proteico-fragole',
    name: 'Riso soffiato con latte proteico e fragole',
    emoji: '🍚',
    description: 'Colazione veloce e leggera, con più proteine di un cereale normale.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'riso-soffiato-kelloggs', grams: 40 },
      { foodId: 'latte-proteico', grams: 250 },
      { foodId: 'fragole', grams: 100 },
    ],
    steps: [
      'Versa il riso soffiato in una ciotola.',
      'Aggiungi il latte proteico.',
      'Completa con le fragole a fette.',
    ],
  },
  {
    id: 'cornflakes-proteine-banana',
    name: 'Cornflakes con proteine in polvere e banana',
    emoji: '🌽',
    description: 'La colazione da cerali classica, con una spinta proteica in più.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'cornflakes-mais', grams: 40 },
      { foodId: 'proteine-isolate', grams: 15 },
      { foodId: 'latte-scremato', grams: 150 },
      { foodId: 'banana', grams: 80 },
    ],
    steps: [
      'Sciogli le proteine in polvere nel latte scremato, mescolando bene.',
      'Versa sui cornflakes in una ciotola.',
      'Completa con la banana a fette.',
    ],
  },
  {
    id: 'yogurt-greco-muesli-mandorle',
    name: 'Yogurt greco con muesli e mandorle',
    emoji: '🥣',
    description: 'Cremoso e sazio, con la croccantezza del muesli.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'yogurt-greco-0', grams: 150 },
      { foodId: 'muesli', grams: 30 },
      { foodId: 'mandorle', grams: 10 },
      { foodId: 'mirtilli', grams: 50 },
    ],
    steps: [
      'Versa lo yogurt greco in una ciotola.',
      'Aggiungi il muesli e mescola.',
      'Completa con mandorle e mirtilli.',
    ],
  },
  {
    id: 'porridge-farina-avena-proteine-vegetali-mela',
    name: 'Porridge di farina d\'avena con proteine vegetali e mela',
    emoji: '🥣',
    description: 'Versione completamente vegetale del porridge proteico.',
    category: 'Colazione',
    tags: ['proteico', 'vegano', 'vegetariano'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farina-avena', grams: 40 },
      { foodId: 'proteine-vegetali', grams: 15 },
      { foodId: 'latte-scremato', grams: 150 },
      { foodId: 'mela', grams: 80 },
    ],
    steps: [
      'Cuoci la farina d\'avena nel latte a fuoco basso per 4-5 minuti, mescolando spesso.',
      'Togli dal fuoco e incorpora le proteine vegetali, mescolando bene.',
      'Completa con la mela a cubetti.',
    ],
  },
  {
    id: 'toast-fiocchi-latte-fragole',
    name: 'Toast con fiocchi di latte e fragole',
    emoji: '🍞',
    description: 'Colazione salata-dolce, pronta in pochi minuti.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano', 'veloce'],
    time: 8,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pane', grams: 60 },
      { foodId: 'fiocchi-latte-0', grams: 100 },
      { foodId: 'fragole', grams: 60 },
    ],
    steps: [
      'Tosta le fette di pane.',
      'Distribuisci sopra i fiocchi di latte.',
      'Completa con le fragole a fette.',
    ],
  },
  {
    id: 'smoothie-bowl-proteico-cornflakes',
    name: 'Smoothie bowl proteico con banana e cornflakes',
    emoji: '🥤',
    description: 'Uno smoothie da mangiare col cucchiaio, con topping croccante.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 8,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'proteine-isolate', grams: 15 },
      { foodId: 'latte-scremato', grams: 200 },
      { foodId: 'banana', grams: 100 },
      { foodId: 'cornflakes-mais', grams: 20 },
    ],
    steps: [
      'Frulla le proteine in polvere con il latte e metà della banana fino a ottenere una crema densa.',
      'Versa in una ciotola.',
      'Completa con il resto della banana a fette e i cornflakes.',
    ],
  },
  {
    id: 'kefir-riso-soffiato-mango',
    name: 'Kefir con riso soffiato e mango',
    emoji: '🥭',
    description: 'Un abbinamento fresco e insolito, pronto in un minuto.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'kefir', grams: 250 },
      { foodId: 'riso-soffiato-kelloggs', grams: 30 },
      { foodId: 'mango', grams: 100 },
      { foodId: 'mandorle', grams: 10 },
    ],
    steps: [
      'Versa il kefir in una ciotola.',
      'Aggiungi il riso soffiato.',
      'Completa con il mango a cubetti e le mandorle.',
    ],
  },
  {
    id: 'yogurt-greco-cornflakes-kiwi',
    name: 'Yogurt greco con cornflakes e kiwi',
    emoji: '🥝',
    description: 'Semplice e veloce, con una nota acidula del kiwi.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'yogurt-greco-0', grams: 150 },
      { foodId: 'cornflakes-mais', grams: 30 },
      { foodId: 'kiwi', grams: 100 },
    ],
    steps: [
      'Versa lo yogurt greco in una ciotola.',
      'Aggiungi i cornflakes.',
      'Completa con il kiwi a fette.',
    ],
  },
  {
    id: 'overnight-oats-farina-avena-kefir-frutti-bosco',
    name: 'Overnight oats con farina d\'avena, kefir e frutti di bosco',
    emoji: '🥣',
    description: 'Da preparare la sera prima: al mattino è già pronta.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farina-avena', grams: 40 },
      { foodId: 'kefir', grams: 200 },
      { foodId: 'mirtilli', grams: 60 },
      { foodId: 'mandorle', grams: 15 },
    ],
    steps: [
      'Mescola la farina d\'avena con il kefir in un barattolo.',
      'Copri e lascia riposare in frigo per almeno 6 ore, o tutta la notte.',
      'Al momento di servire, completa con mirtilli e mandorle.',
    ],
  },
  {
    id: 'uova-avena-mela',
    name: 'Uova strapazzate con avena tostata e mela',
    emoji: '🍳',
    description: 'Colazione salata e dolce insieme, sazia e completa.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano'],
    time: 12,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'uova', grams: 100 },
      { foodId: 'avena', grams: 30 },
      { foodId: 'mela', grams: 100 },
    ],
    steps: [
      'Tosta l\'avena in una padella antiaderente per 2-3 minuti, mescolando spesso.',
      'Strapazza le uova in un\'altra padella fino a cottura desiderata.',
      'Servi le uova con l\'avena tostata e la mela a fette a lato.',
    ],
  },
  {
    id: 'pancake-farina-avena-proteine-fragole',
    name: 'Pancake di farina d\'avena e proteine, farciti con fragole',
    emoji: '🥞',
    description: 'Una variante ancora più proteica del classico pancake proteico.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farina-avena', grams: 40 },
      { foodId: 'albume', grams: 60 },
      { foodId: 'proteine-isolate', grams: 10 },
      { foodId: 'fragole', grams: 80 },
    ],
    steps: [
      'Mescola la farina d\'avena, l\'albume e le proteine in polvere fino a ottenere un composto omogeneo.',
      'Cuoci piccole porzioni di composto in una padella antiaderente calda, 2-3 minuti per lato.',
      'Servi i pancake farciti con le fragole a fette.',
    ],
  },
  {
    id: 'gallette-riso-philadelphia-protein-fragole',
    name: 'Gallette di riso con Philadelphia Protein e fragole',
    emoji: '🍘',
    description: 'Croccante e veloce, con più proteine di una colazione da gallette qualsiasi.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'gallette-riso', grams: 40 },
      { foodId: 'philadelphia-protein', grams: 60 },
      { foodId: 'fragole', grams: 60 },
    ],
    steps: [
      'Spalma il Philadelphia Protein sulle gallette di riso.',
      'Completa con le fragole a fette.',
    ],
  },
  {
    id: 'porridge-avena-yogurt-greco-2-banana',
    name: 'Porridge di avena con yogurt greco e banana',
    emoji: '🥣',
    description: 'Una via di mezzo tra un porridge caldo e uno yogurt bowl.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 40 },
      { foodId: 'yogurt-greco-2', grams: 120 },
      { foodId: 'banana', grams: 80 },
      { foodId: 'mandorle', grams: 10 },
    ],
    steps: [
      'Cuoci l\'avena con un po\' d\'acqua a fuoco basso per 4-5 minuti, mescolando spesso.',
      'Lascia intiepidire, poi incorpora lo yogurt greco.',
      'Completa con la banana a fette e le mandorle.',
    ],
  },
  {
    id: 'fiocchi-latte-cornflakes-mirtilli',
    name: 'Fiocchi di latte con cornflakes e mirtilli',
    emoji: '🧀',
    description: 'Un bowl proteico e croccante insieme, pronto in un minuto.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'fiocchi-latte-0', grams: 150 },
      { foodId: 'cornflakes-mais', grams: 30 },
      { foodId: 'mirtilli', grams: 60 },
    ],
    steps: [
      'Versa i fiocchi di latte in una ciotola.',
      'Aggiungi i cornflakes.',
      'Completa con i mirtilli.',
    ],
  },
  {
    id: 'porridge-farina-avena-albume-mango',
    name: 'Porridge di farina d\'avena con albume e mango',
    emoji: '🥭',
    description: 'La cottura dell\'albume nel porridge lo rende ancora più cremoso.',
    category: 'Colazione',
    tags: ['proteico', 'vegetariano'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farina-avena', grams: 40 },
      { foodId: 'albume', grams: 100 },
      { foodId: 'mango', grams: 100 },
    ],
    steps: [
      'Scalda la farina d\'avena con un po\' d\'acqua a fuoco basso.',
      'Incorpora l\'albume poco alla volta, mescolando continuamente per 4-5 minuti finché il composto non si addensa.',
      'Completa con il mango a cubetti.',
    ],
  },
  {
    id: 'tacchino-verza-patate',
    name: 'Tacchino con verza e patate',
    emoji: '🍗',
    description: 'Un secondo magro e confortante, con un contorno di stagione.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tacchino', grams: 150 },
      { foodId: 'verza', grams: 150 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Lessa le patate a tocchetti finché non sono morbide.',
      'Salta la verza tagliata a listarelle in padella con un filo d\'olio per 6-7 minuti.',
      'Cuoci il tacchino in padella o al forno fino a completa cottura e servi con verza e patate.',
    ],
  },
  {
    id: 'pollo-asparagi-farro',
    name: 'Pollo con asparagi e farro',
    emoji: '🍗',
    description: 'Un piatto unico primaverile, semplice da preparare in mezz\'ora.',
    category: 'Pranzo',
    tags: ['leggero', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pollo', grams: 150 },
      { foodId: 'farro', grams: 90 },
      { foodId: 'asparagi', grams: 150 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Cuoci il farro secondo i tempi indicati sulla confezione.',
      'Salta gli asparagi in padella con un filo d\'olio per 6-7 minuti.',
      'Cuoci il pollo a fette in padella fino a completa cottura e componi il piatto.',
    ],
  },
  {
    id: 'merluzzo-carciofi-patate',
    name: 'Merluzzo con carciofi e patate',
    emoji: '🐟',
    description: 'Un secondo delicato, cotto interamente in padella.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'merluzzo', grams: 180 },
      { foodId: 'carciofi', grams: 150 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Lessa le patate a tocchetti finché non sono morbide.',
      'Salta i carciofi puliti e affettati in padella con un filo d\'olio per 8-10 minuti.',
      'Cuoci il merluzzo in padella per 6-8 minuti e componi il piatto.',
    ],
  },
  {
    id: 'gamberi-fagiolini-riso',
    name: 'Gamberi con fagiolini e riso',
    emoji: '🦐',
    description: 'Fresco e leggero, pronto in venti minuti.',
    category: 'Pranzo/Cena',
    tags: ['leggero', 'proteico'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'gamberi', grams: 180 },
      { foodId: 'fagiolini', grams: 150 },
      { foodId: 'riso', grams: 80 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Lessa o cuoci a vapore i fagiolini per 8-10 minuti.',
      'Salta i gamberi in padella con un filo d\'olio per 3-4 minuti e componi il piatto.',
    ],
  },
  {
    id: 'seitan-cavolo-nero-patate-dolci',
    name: 'Seitan con cavolo nero e patate dolci',
    emoji: '🌾',
    description: 'Un secondo vegetale ricco di proteine, dai sapori decisi.',
    category: 'Cena',
    tags: ['vegano', 'vegetariano', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'seitan', grams: 150 },
      { foodId: 'cavolo-nero', grams: 150 },
      { foodId: 'patate-dolci', grams: 200 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Cuoci le patate dolci a tocchetti in forno o lessate.',
      'Salta il cavolo nero tagliato a listarelle in padella con un filo d\'olio per 8-10 minuti.',
      'Cuoci il seitan alla piastra 3-4 minuti per lato e componi il piatto.',
    ],
  },
  {
    id: 'ceci-bietole-pomodoro',
    name: 'Ceci con bietole e pomodoro',
    emoji: '🫘',
    description: 'Un piatto unico vegetale, confortante e ricco di fibre.',
    category: 'Pranzo',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'ceci', grams: 150 },
      { foodId: 'bietole', grams: 150 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Salta le bietole in padella con un filo d\'olio per 5-6 minuti.',
      'Aggiungi il pomodoro a pezzi e cuoci altri 5 minuti.',
      'Unisci i ceci già cotti e scalda insieme per 5 minuti.',
    ],
  },
  {
    id: 'tonno-fagiolini-patate',
    name: 'Tonno con fagiolini e patate',
    emoji: '🐟',
    description: 'Una versione calda dell\'insalata nizzarda, senza uovo né olive.',
    category: 'Pranzo',
    tags: ['leggero', 'proteico', 'veloce'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tonno', grams: 100 },
      { foodId: 'fagiolini', grams: 150 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Lessa le patate a tocchetti e i fagiolini finché non sono morbidi.',
      'Scola il tonno e uniscilo a patate e fagiolini ancora tiepidi.',
      'Condisci con un filo d\'olio.',
    ],
  },
  {
    id: 'tofu-porri-riso',
    name: 'Tofu con porri e riso',
    emoji: '🧊',
    description: 'Un piatto unico vegetale dal sapore delicato.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tofu', grams: 150 },
      { foodId: 'porri', grams: 150 },
      { foodId: 'riso', grams: 80 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Taglia il tofu a cubetti e rosolalo in padella con un filo d\'olio finché non è dorato.',
      'Aggiungi i porri affettati e salta insieme per 6-7 minuti.',
    ],
  },
  {
    id: 'lenticchie-sedano-carote',
    name: 'Lenticchie con sedano e carote',
    emoji: '🫘',
    description: 'Un classico brodo di legumi, in versione più asciutta.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'lenticchie', grams: 200 },
      { foodId: 'sedano', grams: 100 },
      { foodId: 'carote', grams: 100 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Trita sedano e carote e falli appassire in padella con un filo d\'olio per 5 minuti.',
      'Unisci le lenticchie già cotte e scalda insieme per 8-10 minuti a fuoco basso.',
    ],
  },
  {
    id: 'pollo-cavolo-rosso-quinoa',
    name: 'Pollo con cavolo rosso e quinoa',
    emoji: '🍗',
    description: 'Un piatto unico colorato, con la croccantezza del cavolo rosso.',
    category: 'Pranzo',
    tags: ['leggero', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pollo', grams: 150 },
      { foodId: 'cavolo-rosso', grams: 150 },
      { foodId: 'quinoa', grams: 80 },
      { foodId: 'olio', grams: 7 },
    ],
    steps: [
      'Cuoci la quinoa secondo i tempi indicati sulla confezione.',
      'Salta il cavolo rosso tagliato a listarelle sottili in padella con un filo d\'olio per 6-7 minuti.',
      'Cuoci il pollo a fette in padella fino a completa cottura e componi il piatto.',
    ],
  },
  {
    id: 'calamari-radicchio-orzo',
    name: 'Calamari con radicchio e orzo',
    emoji: '🦑',
    description: 'Un abbinamento insolito tra la dolcezza del calamaro e l\'amaro del radicchio.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'calamaro', grams: 180 },
      { foodId: 'radicchio', grams: 100 },
      { foodId: 'orzo', grams: 90 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Cuoci l\'orzo in acqua bollente salata secondo i tempi indicati.',
      'Salta il radicchio tagliato a listarelle in padella con un filo d\'olio per 4-5 minuti.',
      'Aggiungi i calamari ad anelli e cuoci ancora 3-4 minuti a fuoco vivo.',
    ],
  },
  {
    id: 'fagioli-cicoria-pane',
    name: 'Fagioli con cicoria e pane',
    emoji: '🫘',
    description: 'Un piatto contadino, sazio e ricco di fibre.',
    category: 'Cena',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'fagioli', grams: 200 },
      { foodId: 'cicoria', grams: 150 },
      { foodId: 'pane', grams: 60 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Lessa o salta in padella la cicoria con un filo d\'olio per 6-7 minuti.',
      'Unisci i fagioli già cotti e scalda insieme per 5 minuti.',
      'Servi con il pane a fette.',
    ],
  },
  {
    id: 'edamame-germogli-soia-riso',
    name: 'Edamame con germogli di soia e riso',
    emoji: '🫛',
    description: 'Un piatto unico vegetale dal sapore fresco, ispirato alla cucina asiatica.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'edamame', grams: 100 },
      { foodId: 'germogli-soia', grams: 100 },
      { foodId: 'riso', grams: 80 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Salta gli edamame già scottati e i germogli di soia in padella con un filo d\'olio per 3-4 minuti.',
      'Componi il piatto con il riso come base.',
    ],
  },
  {
    id: 'polpo-sedano-rapa-patate',
    name: 'Polpo con sedano rapa e patate',
    emoji: '🐙',
    description: 'Una variante insolita del classico polpo e patate.',
    category: 'Cena',
    tags: ['proteico'],
    time: 40,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'polpo', grams: 200 },
      { foodId: 'sedano-rapa', grams: 150 },
      { foodId: 'patate', grams: 150 },
      { foodId: 'olio', grams: 8 },
    ],
    steps: [
      'Lessa il polpo in acqua bollente finché non è tenero.',
      'Lessa il sedano rapa e le patate a tocchetti finché non sono morbidi.',
      'Taglia il polpo a pezzi, unisci sedano rapa e patate e condisci con un filo d\'olio.',
    ],
  },
  {
    id: 'manzo-cavoletti-bruxelles-patate',
    name: 'Manzo con cavoletti di Bruxelles e patate',
    emoji: '🥩',
    description: 'Un secondo sostanzioso, con un contorno dal sapore deciso.',
    category: 'Cena',
    tags: ['proteico'],
    time: 30,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'manzo', grams: 100 },
      { foodId: 'cavoletti-bruxelles', grams: 150 },
      { foodId: 'patate', grams: 150 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Lessa le patate a tocchetti finché non sono morbide.',
      'Cuoci i cavoletti di Bruxelles a vapore o lessati per 10-12 minuti, poi saltali in padella con un filo d\'olio.',
      'Cuoci il manzo in padella fino a cottura desiderata e componi il piatto.',
    ],
  },
];

export function calcRecipeTotals(recipe, servings) {
  const scale = servings / recipe.baseServings;
  return recipe.ingredients.reduce(
    (acc, ing) => {
      const food = FOODS.find((f) => f.id === ing.foodId);
      const grams = ing.grams * scale;
      const c = calc(food, grams);
      return {
        kcal: acc.kcal + c.kcal,
        protein: +(acc.protein + c.protein).toFixed(1),
        carbs: +(acc.carbs + c.carbs).toFixed(1),
        fat: +(acc.fat + c.fat).toFixed(1),
        fiber: +(acc.fiber + c.fiber).toFixed(1),
      };
    },
    { kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }
  );
}

export function scaledIngredients(recipe, servings) {
  const scale = servings / recipe.baseServings;
  return recipe.ingredients.map((ing) => {
    const food = FOODS.find((f) => f.id === ing.foodId);
    return { food, grams: Math.round(ing.grams * scale) };
  });
}
