import { FOODS, calc } from './foods';

export const RECIPES = [
  {
    id: 'pasta-tonno-pomodoro',
    name: 'Pasta al tonno e pomodoro',
    emoji: '🍝',
    description: 'Un piatto veloce e proteico, pronto in 15 minuti con pochi ingredienti.',
    category: 'Pranzo',
    tags: ['proteico', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pasta', grams: 80 },
      { foodId: 'tonno', grams: 100 },
      { foodId: 'pomodoro', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Porta a bollore l\'acqua e cuoci la pasta secondo i tempi indicati sulla confezione.',
      'Nel frattempo scalda l\'olio in padella e aggiungi il pomodoro tagliato a pezzi.',
      'Aggiungi il tonno sgocciolato e scalda per 2-3 minuti.',
      'Scola la pasta e saltala in padella con il condimento per un minuto.',
    ],
  },
  {
    id: 'toast-avocado-uovo',
    name: 'Toast con avocado e uovo',
    emoji: '🥑',
    description: 'Colazione salata bilanciata tra grassi buoni e proteine.',
    category: 'Colazione',
    tags: ['vegetariano', 'veloce'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pane', grams: 60 },
      { foodId: 'avocado', grams: 70 },
      { foodId: 'uova', grams: 100 },
    ],
    steps: [
      'Tosta le fette di pane integrale.',
      'Schiaccia l\'avocado con una forchetta e distribuiscilo sul pane.',
      'Cuoci l\'uovo come preferisci (in camicia, sodo o strapazzato) e adagialo sopra.',
    ],
  },
  {
    id: 'pollo-riso-spinaci',
    name: 'Pollo, riso e spinaci',
    emoji: '🍗',
    description: 'Il classico piatto post-allenamento: semplice, completo, senza sorprese.',
    category: 'Cena',
    tags: ['proteico'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pollo', grams: 150 },
      { foodId: 'riso', grams: 80 },
      { foodId: 'spinaci', grams: 100 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Cuoci il petto di pollo in padella o al forno fino a completa cottura.',
      'Salta velocemente gli spinaci in padella con un filo d\'olio.',
      'Componi il piatto con riso, pollo a fette e spinaci.',
    ],
  },
  {
    id: 'yogurt-banana-mandorle',
    name: 'Yogurt, banana e mandorle',
    emoji: '🥣',
    description: 'Uno snack o una colazione pronta in cinque minuti, senza cottura.',
    category: 'Colazione',
    tags: ['vegetariano', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'yogurt', grams: 150 },
      { foodId: 'banana', grams: 100 },
      { foodId: 'mandorle', grams: 15 },
    ],
    steps: [
      'Versa lo yogurt greco in una ciotola.',
      'Taglia la banana a rondelle e aggiungila.',
      'Completa con le mandorle, intere o tritate grossolanamente.',
    ],
  },
  {
    id: 'insalata-mediterranea',
    name: 'Insalata mediterranea con tonno',
    emoji: '🥗',
    description: 'Fresca, leggera, perfetta per un pranzo estivo o una cena veloce.',
    category: 'Pranzo',
    tags: ['leggero', 'veloce'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'pomodoro', grams: 200 },
      { foodId: 'tonno', grams: 80 },
      { foodId: 'olio', grams: 10 },
      { foodId: 'pane', grams: 40 },
    ],
    steps: [
      'Taglia il pomodoro a spicchi e disponilo in una ciotola.',
      'Aggiungi il tonno sgocciolato.',
      'Condisci con l\'olio EVO.',
      'Servi con il pane a fette, tostato o a crostini.',
    ],
  },
  {
    id: 'buddha-bowl-quinoa-ceci',
    name: 'Buddha bowl con quinoa e ceci',
    emoji: '🥗',
    description: 'Una ciotola completa, colorata e completamente vegetale.',
    category: 'Pranzo',
    tags: ['vegano', 'vegetariano', 'proteico'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'quinoa', grams: 80 },
      { foodId: 'ceci', grams: 100 },
      { foodId: 'avocado', grams: 50 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci la quinoa secondo i tempi indicati sulla confezione.',
      'Scola i ceci se in barattolo, oppure scaldali se già cotti.',
      'Componi la bowl con quinoa, ceci, avocado a fette e pomodoro a cubetti.',
      'Condisci con un filo d\'olio EVO.',
    ],
  },
  {
    id: 'salmone-forno-patate',
    name: 'Salmone al forno con patate',
    emoji: '🐟',
    description: 'Un secondo completo, ricco di omega-3 e facile da preparare.',
    category: 'Cena',
    tags: ['proteico'],
    time: 30,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'salmone', grams: 150 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'spinaci', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a tocchetti e cuocile in forno a 200°C per circa 25 minuti.',
      'Inforna il salmone condito con un filo d\'olio per gli ultimi 15 minuti.',
      'Salta velocemente gli spinaci in padella con un filo d\'olio.',
      'Componi il piatto con salmone, patate e spinaci.',
    ],
  },
  {
    id: 'tofu-saltato-verdure',
    name: 'Tofu saltato con verdure',
    emoji: '🧊',
    description: 'Veloce, leggero, completamente vegetale.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tofu', grams: 150 },
      { foodId: 'zucchine', grams: 150 },
      { foodId: 'carote', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia il tofu a cubetti e rosolalo in padella con un filo d\'olio finché non è dorato.',
      'Aggiungi le verdure tagliate a listarelle sottili.',
      'Salta tutto insieme per 8-10 minuti a fuoco medio-alto.',
    ],
  },
  {
    id: 'farro-mozzarella-pomodoro',
    name: 'Insalata di farro con mozzarella e pomodoro',
    emoji: '🥣',
    description: 'Fresca e sazia, perfetta anche portata fuori casa.',
    category: 'Pranzo',
    tags: ['vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farro', grams: 100 },
      { foodId: 'mozzarella', grams: 100 },
      { foodId: 'pomodoro', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il farro e lascialo raffreddare.',
      'Taglia la mozzarella a cubetti e il pomodoro a pezzi.',
      'Unisci tutto e condisci con olio EVO, sale e origano a piacere.',
    ],
  },
  {
    id: 'porridge-avena-mirtilli',
    name: 'Porridge di avena con mirtilli e mandorle',
    emoji: '🥣',
    description: 'Colazione calda, sazia a lungo grazie alle fibre dell\'avena.',
    category: 'Colazione',
    tags: ['vegetariano', 'veloce'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 50 },
      { foodId: 'latte-scremato', grams: 200 },
      { foodId: 'mirtilli', grams: 50 },
      { foodId: 'mandorle', grams: 10 },
    ],
    steps: [
      'Cuoci l\'avena nel latte a fuoco basso per circa 5 minuti, mescolando spesso.',
      'Versa in una ciotola.',
      'Completa con mirtilli freschi e mandorle.',
    ],
  },
  {
    id: 'seitan-piastra-verdure',
    name: 'Seitan alla piastra con verdure miste',
    emoji: '🌾',
    description: 'Un secondo vegetale ricco di proteine, pronto in venti minuti.',
    category: 'Cena',
    tags: ['vegano', 'vegetariano', 'proteico'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'seitan', grams: 150 },
      { foodId: 'zucchine', grams: 100 },
      { foodId: 'peperoni', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia il seitan a fette non troppo sottili.',
      'Cuocilo alla piastra 3-4 minuti per lato.',
      'Nel frattempo salta le verdure in padella con un filo d\'olio.',
      'Servi il seitan con le verdure a fianco.',
    ],
  },
  {
    id: 'lenticchie-stufate',
    name: 'Lenticchie stufate',
    emoji: '🫘',
    description: 'Un classico confortante, ricco di fibre e proteine vegetali.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'lenticchie', grams: 200 },
      { foodId: 'cipolla', grams: 50 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Soffriggi la cipolla tritata nell\'olio finché non appassisce.',
      'Aggiungi il pomodoro a pezzi e cuoci 5 minuti.',
      'Unisci le lenticchie già cotte e scalda insieme per altri 5 minuti.',
    ],
  },
  {
    id: 'smoothie-proteico-banana',
    name: 'Smoothie proteico alla banana',
    emoji: '🥤',
    description: 'Pronto in cinque minuti, comodo dopo l\'allenamento.',
    category: 'Snack',
    tags: ['proteico', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'banana', grams: 100 },
      { foodId: 'proteine-isolate', grams: 30 },
      { foodId: 'latte-scremato', grams: 200 },
    ],
    steps: [
      'Metti tutti gli ingredienti nel frullatore.',
      'Frulla fino a ottenere una consistenza liscia e omogenea.',
      'Servi subito.',
    ],
  },
  {
    id: 'pancake-avena-albume',
    name: 'Pancake proteici con farina d\'avena e albume',
    emoji: '🥞',
    description: 'Colazione o post-allenamento, ricca di proteine e senza zuccheri aggiunti.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 40 },
      { foodId: 'albume', grams: 120 },
      { foodId: 'banana', grams: 50 },
    ],
    steps: [
      'Frulla l\'avena fino a ottenere una farina fine.',
      'Schiaccia la banana e uniscila alla farina d\'avena e all\'albume, mescolando fino a ottenere un composto omogeneo.',
      'Cuoci piccole porzioni di composto in una padella antiaderente calda, 2-3 minuti per lato.',
    ],
  },
  {
    id: 'porridge-proteico-frutta-yogurt',
    name: 'Porridge proteico con frutta e yogurt greco',
    emoji: '🥣',
    description: 'Avena cotta nel latte proteico, completata con yogurt greco e frutta fresca.',
    category: 'Colazione',
    tags: ['proteico'],
    time: 10,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 50 },
      { foodId: 'latte-proteico', grams: 200 },
      { foodId: 'yogurt-greco-0', grams: 80 },
      { foodId: 'mirtilli', grams: 50 },
    ],
    steps: [
      'Cuoci l\'avena nel latte proteico a fuoco basso per circa 5 minuti, mescolando spesso.',
      'Versa in una ciotola e lascia intiepidire un paio di minuti.',
      'Completa con lo yogurt greco e i mirtilli freschi.',
    ],
  },
  {
    id: 'frittata-albumi-spinaci',
    name: 'Frittata di albumi con spinaci',
    emoji: '🍳',
    description: 'Molte proteine, pochissimi grassi: un classico da palestra.',
    category: 'Colazione/Pranzo',
    tags: ['proteico', 'leggero', 'veloce'],
    time: 12,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'albume', grams: 200 },
      { foodId: 'spinaci', grams: 100 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Salta velocemente gli spinaci in padella con un filo d\'olio finché non appassiscono.',
      'Versa gli albumi sopra gli spinaci nella stessa padella.',
      'Cuoci a fuoco medio-basso, muovendo leggermente i bordi, finché non si rapprendono del tutto.',
    ],
  },
  {
    id: 'pollo-patate-broccoli-forno',
    name: 'Pollo, patate e broccoli al forno',
    emoji: '🍗',
    description: 'Il pasto da palestra per eccellenza: semplice, prevedibile, efficace.',
    category: 'Pranzo/Cena',
    tags: ['proteico'],
    time: 35,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'pollo', grams: 180 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'broccoli', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a tocchetti e disponile su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Aggiungi il pollo a pezzi e i broccoli, e continua la cottura per altri 15 minuti.',
    ],
  },
  {
    id: 'riso-tonno-piselli',
    name: 'Riso con tonno e piselli',
    emoji: '🍚',
    description: 'Pratico da preparare in anticipo, ottimo dopo l\'allenamento.',
    category: 'Pranzo',
    tags: ['proteico', 'veloce', 'post-workout'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'riso', grams: 100 },
      { foodId: 'tonno', grams: 100 },
      { foodId: 'piselli', grams: 80 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata.',
      'Scalda i piselli in padella con un filo d\'olio.',
      'Scola il riso, unisci il tonno sgocciolato e i piselli, mescola e servi.',
    ],
  },
  {
    id: 'overnight-oats-proteici',
    name: 'Overnight oats proteici',
    emoji: '🌙',
    description: 'Prepari la sera prima, la mattina è già pronta: perfetta per chi ha poco tempo.',
    category: 'Colazione',
    tags: ['proteico', 'veloce'],
    time: 5,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'avena', grams: 50 },
      { foodId: 'yogurt-greco-2', grams: 100 },
      { foodId: 'latte-proteico', grams: 100 },
      { foodId: 'mirtilli', grams: 50 },
    ],
    steps: [
      'Mescola avena, yogurt greco e latte proteico in un barattolo con coperchio.',
      'Aggiungi i mirtilli, chiudi e lascia riposare in frigorifero per almeno 6 ore, meglio tutta la notte.',
      'Al mattino mescola bene prima di mangiare, aggiungendo altro latte se troppo denso.',
    ],
  },
  {
    id: 'tacchino-riso-integrale-zucchine',
    name: 'Tacchino con riso integrale e zucchine',
    emoji: '🍗',
    description: 'Magro, leggero, facile da preparare in più porzioni per la settimana.',
    category: 'Cena',
    tags: ['proteico', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'tacchino', grams: 180 },
      { foodId: 'riso-integrale', grams: 150 },
      { foodId: 'zucchine', grams: 150 },
      { foodId: 'olio', grams: 5 },
    ],
    steps: [
      'Cuoci il riso integrale secondo i tempi indicati sulla confezione.',
      'Cuoci la fesa di tacchino in padella a fuoco medio, 4-5 minuti per lato.',
      'Salta le zucchine a rondelle in padella con un filo d\'olio.',
      'Componi il piatto con riso, tacchino a fette e zucchine.',
    ],
  },
  {
    id: 'merluzzo-patate-finocchi',
    name: 'Merluzzo al forno con patate e finocchi',
    emoji: '🐟',
    description: 'Un secondo leggero e delicato, cotto tutto insieme in forno.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 35,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'merluzzo', grams: 180 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'finocchi', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia patate e finocchi a fette sottili e disponili su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Aggiungi il merluzzo condito con un filo d\'olio e continua la cottura per altri 12-15 minuti.',
    ],
  },
  {
    id: 'gamberi-couscous-zucchine',
    name: 'Gamberi saltati con couscous e zucchine',
    emoji: '🦐',
    description: 'Un piatto unico dal sapore fresco, pronto in mezz\'ora.',
    category: 'Pranzo/Cena',
    tags: ['leggero', 'veloce'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'gamberi', grams: 180 },
      { foodId: 'couscous', grams: 80 },
      { foodId: 'zucchine', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Prepara il couscous seguendo le indicazioni sulla confezione.',
      'Taglia le zucchine a cubetti e saltale in padella con un filo d\'olio per 5-6 minuti.',
      'Aggiungi i gamberi e cuoci ancora 3-4 minuti, finché non diventano rosati.',
      'Componi il piatto con il couscous come base, gamberi e zucchine sopra.',
    ],
  },
  {
    id: 'farro-ceci-verdure',
    name: 'Farro con ceci e verdure miste',
    emoji: '🥣',
    description: 'Un piatto completamente vegetale, sazio grazie a fibre e legumi.',
    category: 'Pranzo',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 25,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'farro', grams: 90 },
      { foodId: 'ceci', grams: 120 },
      { foodId: 'zucchine', grams: 100 },
      { foodId: 'pomodoro', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il farro secondo i tempi indicati sulla confezione e lascialo intiepidire.',
      'Salta le zucchine a cubetti in padella con un filo d\'olio per 5 minuti.',
      'Unisci il farro, i ceci e il pomodoro a pezzi.',
      'Mescola bene e condisci con un filo d\'olio a crudo.',
    ],
  },
  {
    id: 'melanzane-gratinate-pomodoro-mozzarella',
    name: 'Melanzane gratinate con pomodoro e mozzarella',
    emoji: '🍆',
    description: 'Una versione più semplice e veloce di un grande classico.',
    category: 'Cena',
    tags: ['vegetariano'],
    time: 35,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'melanzane', grams: 250 },
      { foodId: 'pomodoro', grams: 150 },
      { foodId: 'mozzarella', grams: 100 },
      { foodId: 'parmigiano', grams: 15 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le melanzane a fette e grigliale in padella o su una piastra finché non sono morbide.',
      'Disponi le melanzane a strati in una teglia, alternando con pomodoro a pezzi e mozzarella.',
      'Completa con parmigiano grattugiato e un filo d\'olio.',
      'Cuoci in forno a 200°C per 15-18 minuti, finché la superficie non è dorata.',
    ],
  },
  {
    id: 'orzo-verdure-mozzarella',
    name: 'Insalata di orzo con verdure e mozzarella',
    emoji: '🥗',
    description: 'Fresca e pratica, ottima anche preparata in anticipo.',
    category: 'Pranzo',
    tags: ['vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'orzo', grams: 90 },
      { foodId: 'pomodoro', grams: 120 },
      { foodId: 'peperoni', grams: 80 },
      { foodId: 'mozzarella', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci l\'orzo in acqua bollente salata secondo i tempi indicati, poi scolalo e lascialo raffreddare.',
      'Taglia pomodoro, peperoni e mozzarella a cubetti.',
      'Unisci tutto all\'orzo e condisci con un filo d\'olio.',
    ],
  },
  {
    id: 'manzo-patate-broccoli-forno',
    name: 'Manzo con patate e broccoli al forno',
    emoji: '🥩',
    description: 'Un secondo sostanzioso, cotto interamente al forno in un\'unica teglia.',
    category: 'Cena',
    tags: ['proteico'],
    time: 35,
    difficulty: 'Media',
    baseServings: 1,
    ingredients: [
      { foodId: 'manzo', grams: 180 },
      { foodId: 'patate', grams: 200 },
      { foodId: 'broccoli', grams: 150 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Taglia le patate a tocchetti e disponile su una teglia con un filo d\'olio.',
      'Cuoci in forno a 200°C per 20 minuti.',
      'Aggiungi il manzo a fette e i broccoli, e continua la cottura per altri 15 minuti.',
    ],
  },
  {
    id: 'riso-edamame-verdure-saltate',
    name: 'Riso con edamame e verdure saltate',
    emoji: '🍚',
    description: 'Piatto unico vegetale ispirato alla cucina asiatica, pronto in 20 minuti.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'veloce'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'riso', grams: 90 },
      { foodId: 'edamame', grams: 100 },
      { foodId: 'carote', grams: 80 },
      { foodId: 'peperoni', grams: 80 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci il riso in acqua bollente salata secondo i tempi indicati.',
      'Taglia carote e peperoni a listarelle sottili e saltali in padella con un filo d\'olio per 5-6 minuti.',
      'Aggiungi gli edamame già scottati e scalda insieme per 2-3 minuti.',
      'Unisci il riso scolato e mescola bene prima di servire.',
    ],
  },
  {
    id: 'sgombro-finocchi-arancia',
    name: 'Sgombro con insalata di finocchi e arancia',
    emoji: '🐟',
    description: 'Un abbinamento fresco tra pesce azzurro e note agrumate.',
    category: 'Cena',
    tags: ['leggero', 'proteico'],
    time: 15,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'sgombro', grams: 150 },
      { foodId: 'finocchi', grams: 150 },
      { foodId: 'arancia', grams: 100 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Cuoci lo sgombro in padella o al forno finché non è cotto.',
      'Affetta finemente i finocchi e l\'arancia a spicchi.',
      'Componi l\'insalata con finocchi e arancia, condita con un filo d\'olio.',
      'Servi lo sgombro accanto all\'insalata.',
    ],
  },
  {
    id: 'fagioli-umido-pane-integrale',
    name: 'Fagioli in umido con pane integrale',
    emoji: '🫘',
    description: 'Un piatto povero solo nel nome: sazio, economico e ricco di fibre.',
    category: 'Pranzo/Cena',
    tags: ['vegano', 'vegetariano', 'leggero'],
    time: 20,
    difficulty: 'Facile',
    baseServings: 1,
    ingredients: [
      { foodId: 'fagioli', grams: 200 },
      { foodId: 'cipolla', grams: 50 },
      { foodId: 'pomodoro', grams: 120 },
      { foodId: 'pane', grams: 60 },
      { foodId: 'olio', grams: 10 },
    ],
    steps: [
      'Soffriggi la cipolla tritata nell\'olio finché non appassisce.',
      'Aggiungi il pomodoro a pezzi e cuoci per 5 minuti.',
      'Unisci i fagioli già cotti e lascia insaporire per altri 8-10 minuti a fuoco basso.',
      'Servi con il pane integrale a fette.',
    ],
  },
];

export function calcRecipeTotals(recipe, servings) {
  const scale = servings / recipe.baseServings;
  return recipe.ingredients.reduce(
    (acc, ing) => {
      const food = FOODS.find((f) => f.id === ing.foodId);
      const grams = ing.grams * scale;
      const c = calc(food, grams);
      return {
        kcal: acc.kcal + c.kcal,
        protein: +(acc.protein + c.protein).toFixed(1),
        carbs: +(acc.carbs + c.carbs).toFixed(1),
        fat: +(acc.fat + c.fat).toFixed(1),
        fiber: +(acc.fiber + c.fiber).toFixed(1),
      };
    },
    { kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }
  );
}

export function scaledIngredients(recipe, servings) {
  const scale = servings / recipe.baseServings;
  return recipe.ingredients.map((ing) => {
    const food = FOODS.find((f) => f.id === ing.foodId);
    return { food, grams: Math.round(ing.grams * scale) };
  });
}
